### ISSUE TITLE
Using v3 ES modules under jest

### ISSUE THREAD

**Issue by youngbob** [panva/jose#110]
When using the ES module imports (with typescript + babel), the type checking and build works fine, but running under jest gives me errors like `Cannot find module 'jose/jwe/compact/decrypt'`

I was able to work around by adding this to my jest config:

```javascript
moduleNameMapper: {
    'jose/jwe/compact/decrypt':
      '<rootDir>/node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js',
    'jose/jwe/compact/encrypt':
      '<rootDir>/node_modules/jose/dist/node/cjs/jwe/compact/encrypt.js',
    'jose/jwk/parse':
      '<rootDir>/node_modules/jose/dist/node/cjs/jwk/parse.js',
  },
```

Is there a better solution?

**Comment by panva** [comment]
#105

**Comment by jschmold** [comment]
Hey, I managed to find a resolution to this. I am using NestJS, and tearing out Jest would've been a _massive_ pain.

I have 2 locations where there is a jest config. 1 in the package.json, and another in the `test/` directory for integration testing.

```json
    "moduleNameMapper": {
      ....
      "jose(.*)": "<rootDir>/../node_modules/jose/dist/node/cjs/$1.js"
    },
```

This may require _slight_ adjustments depending on very specific testing environments (folder structure in particular), but in general, this works just fine and does not require a 1-line-per-file approach.
