### ISSUE TITLE
Error: Cannot find module 'jose'

### ISSUE THREAD

**Issue by sarathjasrin** [panva/jose#120]
I tried use it for azure functions. It's not seems working.

I installed `npm install --save-dev @types/node` but still getting the issue.

Node version: **v10.15.3**

**Comment by panva** [comment]
https://github.com/panva/jose#runtime-support-matrix

**Comment by sarathjasrin** [comment]
Hi tried with Azure funtions. Node version is **v14.15.0**. There also I'm getting the same error.

**Comment by panva** [comment]
In that case please follow the documentation. It shows how each individual module is to be imported. There's no "jose" root module.
