### ISSUE TITLE
Compile fail CryptoKey

### ISSUE THREAD

**Issue by giovanni9793** [panva/jose#126]
I don't know if the problem was a bug or me doing something wrong.
When I try to build my package, something go wrong.

```
yarn run v1.22.5
$ rm -rf ./dist/* && mkdir -p ./dist && tsc
node_modules/jose/dist/types/types.d.ts:92:35 - error TS2304: Cannot find name 'CryptoKey'.

92 export type KeyLike = KeyObject | CryptoKey | Uint8Array
                                     ~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "/bin/bash '-c', 'yarn run build'" terminated with exit code: 2.
```
Node 14, same error on docker.

**Comment by panva** [comment]
Please update your typescript version. The CryptoKey interface is part of its standard es6 types definition.

**Comment by panva** [comment]
Not sure if it helped but i've referenced the dom lib explicitly now in [v3.3.2](https://diff.intrinsic.com/jose/3.3.1/3.3.2)
