### ISSUE TITLE
question: How do I get the thumbprint of a key

### ISSUE THREAD

**Issue by mcoeur** [panva/jose#14]
Hi,

I'm kind of new to the world of JW*, and I need to get the thumbprint of a key, how do I do that using this library ? 

(I already imported the key from a file. I need to create a JWE and, according to the document i got, I have to add the key's thumbprint to the protected headers)

Best regards,

**Comment by panva** [comment]
Hi @mcoeur 

The [JWK Thumbprint](https://tools.ietf.org/html/rfc7638) is calculated and available on a `JWK.Key` instance as the `kid` property getter.

To add the `kid` header parameter to a JWE protected header just follow the [doc](https://github.com/panva/jose/blob/master/docs/README.md#jweencryptcleartext-key-protected)


```js
jose.JWE.encrypt('...', key, { kid: key.kid })
```

**Comment by mcoeur** [comment]
This is perfect, thank you !
