### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by exdevop** [panva/jose#142]
I keep on getting this error since I installed this module yesterday

```js
 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/dev/projects/api/node_modules/jose/package.json
at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
at resolveExports (internal/modules/cjs/loader.js:432:36)
at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/home/dev/projects/api/src/utils/utils.ts:5:14)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

```

**Environment:**

- `jose` version: [e.g. v3.5.1]
- affected runtime is: [e.g. Node.js 14.15.4 `npm` version 6.14.11

My tscongig:
```js
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "target": "es6",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "lib": [
      "es2015"
    ]
  },
  "include": [
    "src/**/*"
  ]
}
```
Possibly related dependencies I use:
```js
{"typescript": "^4.1.3",
    "webpack": "^5.12.3",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "^3.11.1"
  },
```

**Comment by panva** [comment]
Please follow the issue template if you intend to file a bug. This description does not help to reproduce anything. 

Nevertheless, this is most likely an issue in your environment, so open a q&a discussion.  With more details and most importantly steps to reproduce, node version, code, etc, ... details!

**Comment by exdevop** [comment]
This is an import issue I have really had for more than 24 hours. Anyway, I just Found out you have latest updates two days ago with different import style and other changes. Fixing the imports seem to help me.

**Comment by panva** [comment]
So, following the docs helped. Nice.

**Comment by wraybowling** [comment]
Got a link? fell into the same rabbit hole myself and this felt like a dead end.

**Comment by joelviel** [comment]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .....\node_modules\jose\package.json

**Comment by emclab** [comment]
Same error

**Comment by panva** [comment]
I will repeat again, 

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/jose/package.json` means you're doing require/import of just `jose`. Please refer to each individual module's documentation on how to require/import the respective functions.

Instead of, e.g. `const { SignJWT } = require('jose/jwt/sign')` you're probably doing something like `const jose = require('jose')`.

Follow the documentation.
