### ISSUE TITLE
Build issues on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by jk89** [panva/jose#147]
I ran npm run build-all and it did not work.

Had some issues with the find commands when running them on my system, if maxdepth is used in find it likes to be the first named argument for some reason. I also had to play with the sed inline replace to get it to work.

Code to reproduce the behaviour:

```bash
npm run build-all
```

**Expected behaviour**
Build scripts should work on debian (ubuntu) systems.

**Environment:**

- `jose` version: latest
- affected runtime is:  Node.js v10.19.0, Ubuntu 20.04.1 LTS

**Additional context**
Here is the diff I applied to the package.json to get this working for my environment:

`-    "runtime:find": "find src/runtime -not -name '*.d.ts' -maxdepth 1 -type f -print0",`
`+    "runtime:find": "find src/runtime -maxdepth 1 -type f -not -name \"*.d.ts\" -print0",`
`-    "runtime:refs": "run-s -s runtime:find | xargs -0 sed -i '' -e \"s/'\\.\\.\\//'\\.\\//g\" -e \"s/'\\.\\/\\.\\./'../g\"",`
`+    "runtime:refs": "find src/runtime/ -maxdepth 1 -type f -not -name \"*.d.ts\" -exec sed -i -e \"s/'\\.\\.\\//'\\.\\//g\" -e \"s/'\\.\\/\\.\\./'../g\" '{}' ';'",`

Perhaps its worth mentioning something in the docs (troubleshooting etc) if you agree?

**Comment by panva** [comment]
https://github.com/panva/jose/blob/main/.github/workflows/test.yml Lines 43 and 44
