### ISSUE TITLE
question: PS256 signatures fail to validate in jwt.io

### ISSUE THREAD

**Issue by neilwashere** [panva/jose#16]
Hello, I have come to your library specifically looking to generate signatures with the **PS256** alg. I am coming from a different lib that may possibly using the same underlying crypto but as this lib requires node >=11 I was hopeful it would resolve the apparent issue I am facing.

The problem I have is that our recipients are failing verification when we have signed with PS256. I'm using jwt.io as an independent source of verification but I can't seem to generate a signature that will pass validation. I'm not sure what jwt.io are using on the backend but whatever it is, I am at a loss.

I've tried using my own private cert as well as using a generated key with pem extraction

```ts
       import { JWK, JWS } from "@panva/jose";
       import moment = require("moment");
       const jwkToPem = require("jwk-to-pem");

       const key = await JWK.generate("RSA", 512, { use: "sig"});
       const payload = { foo: "baz", exp: Math.round(moment.now() / 1000 + 3600) };
       const pPem = jwkToPem(key);

       const sig = JWS.sign(payload, key, {alg: "PS256"});
       // resultant sig does not validate in jwt.io
```
I respect this may simply be an issue with jwt.io but as my recipient is rejecting my signatures I am wondering if there is a more subtle issue at hand or if I am just doing something completely wrong.
Any ideas?

**Comment by panva** [comment]
Hi @neilwashere,

Can you provide the specific JWS, private and public PEMs? I'm happy to look into it.

jwt.io does not do any "backend", your key material and potentially PII containing tokens remain in your browsers, it's using webpacked [node-jose](https://github.com/cisco/node-jose)

**Comment by panva** [comment]
Both node-jose in node and jsonwebtoken are able to verify the signatures, the OIDC certification software does too. Therefore this has to be issue specific to https://jwt.io implementation or the browser specific implementation from node-jose

**Comment by neilwashere** [comment]
Thank @panva. I think this may just be jwt.io as this is the same issue https://github.com/brianloveswords/node-jws/issues/85.

Thanks for the response!

**Comment by panva** [comment]
I've poked my colleague (@Sambego) to take a look at this, no promises tho.

**Comment by panva** [comment]
@neilwashere please confirm it's fixed with 0.11.0

**Comment by panva** [comment]
Bottom line 

https://tools.ietf.org/html/rfc7518#section-3.5

> A key of size 2048 bits or larger MUST be used with this algorithm.

and

> The size of the salt value is the same size as
> the hash function output.  All other algorithm parameters use the
> defaults specified in Appendix A.2.3 of RFC 3447.

**Comment by neilwashere** [comment]
@panva confirmed working :+1:  :tada:

**Comment by panva** [comment]
Thanks.
