### ISSUE TITLE
Cannot use jose to deploy AWS lambda using cladua js

### ISSUE THREAD

**Issue by gjorgjivladimirov-allocate** [panva/jose#179]
I cannot use jose in my AWS lambda. When I try to deploy patch(or create new lambda) using cladua js. I always get this error:

`added 175 packages from 104 contributors in 9.036s

1 package is looking for funding
  run `npm fund` for details

validating package
Error: **Cannot find module 'jose/jwt/verify'**
Require stack:
-C:\Users\{User}\AppData\Local\Temp\Lr2Xky\mylambda-1.0.1-oFBtjh\package\index.js
 .........`

* I also had issues with jose when I wrote my unit test with jest but as I workaround for jet i use `moduleNameMapper..` to resolve that obstacle.

My package.json looks like:
```
....
"files": [
		"src/**/*.js",
		"*.js",
		"package.json"
	],
	"keywords": [
		"authorizer"
	],
	"author": "test-user",
	"license": "UNLICENSED",
	"devDependencies": {
		"@types/jest": "^26.0.22",
		"@types/node": "^12.14.0",
		"claudia": "^5.4.0",
		"jest": "^26.6.3",
		"npm": "^6.11.3",
		"ts-jest": "^26.5.4",
		"tslint": "^6.1.3",
		"typescript": "^4.2.3"
	},
	"jest": {
		"preset": "ts-jest",
		"verbose": true,
		"testEnvironment": "node",
		"transform": {
			"^.+\\.ts$": "ts-jest"
		},
		"moduleFileExtensions": [
			"ts",
			"tsx",
			"js",
			"jsx",
			"json",
			"node"
		],
		"testRegex": "\\.spec\\.ts$",
		"moduleNameMapper": {
			"^jose/(.*)$": "<rootDir>/node_modules/jose/dist/node/cjs/$1"
		}
	},
	"dependencies": {
		"jose": "npm:jose-node-cjs-runtime@^3.11.2"
	}
```

Environment: 
   Nodejs version: v12.16.0
   Npm version: 6.13.4

**Comment by panva** [comment]
> I cannot use jose in my AWS lambda. When I try to deploy patch(or create new lambda) using cladua js. I always get this error:
>
> Environment:
> Nodejs version: v12.16.0
> Npm version: 6.13.4

<img width="826" alt="Screenshot 2021-04-14 at 15 13 58" src="https://user-images.githubusercontent.com/241506/114716250-2932fe00-9d34-11eb-8ecc-39576e23390e.png">

**Comment by gjorgjivladimirov-allocate** [comment]
Thank you panva.. I wasn't aware of that.
