### ISSUE TITLE
Build failure on Debian Buster

### ISSUE THREAD

**Issue by babelouest** [panva/jose#182]
**Describe the bug**

On a fresh install of jose-3.11.5 or the master branch, I can't build the package.
I get different errors depending on the target

**To Reproduce**

## npm run build

```shell
$ npm run build
> jose@3.11.5 build /home/nico/workspace/node-jose/jose-3.11.5
> tsc

Version 4.2.4
Syntax:   tsc [options] [file...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
          tsc --build tsconfig.json
```

## npm run build-all

```shell
$ npm run build-all
> jose@3.11.5 runtime:refs /workspace/node-jose/jose-3.11.5
> run-s -s runtime:find | xargs -0 sed -i '' -e "s/'\.\.\//'\.\//g" -e "s/'\.\/\.\./'../g"

find: warning: you have specified the -maxdepth option after a non-option argument -not, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

sed: can't read : No such file or directory
```

## npm run build-fast:browser

```shell
> jose@3.11.5 runtime:refs /workspace/node-jose/jose-3.11.5
> run-s -s runtime:find | xargs -0 sed -i '' -e "s/'\.\.\//'\.\//g" -e "s/'\.\/\.\./'../g"

find: warning: you have specified the -maxdepth option after a non-option argument -not, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

sed: can't read : No such file or directory
```

Is there something missing in my configuration?

**Environment:**

- `jose` version: 3.11.5
- affected runtime is: npm 5.8.0 and nodejs v10.24.0
- other relevant library versions: Debian Buster

**Additional context**

- [X] the bug is happening on latest `jose` too.
- [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
The build scripts are set up to run in CI and my local macbook. That's it. Look at the test.yml to see what runs in ci to make the build scripts work on linux.

**Comment by panva** [comment]
If you'd like to work on it i'm thinking of moving the scripts to make/Makefile to have universal ones. But i'm torn, i don't think it's worth the effort.

**Comment by babelouest** [comment]
I'd like to use your project on a web application designed for end-to-end encryption.

A webservice hosts JWE for users, the key to decypher the JWE must not be available to the server except in an encrypted form.

One of the goal is the reproducibility: anyone can build the whole project from the source only.

Therefore I'm willing to help you allowing enhancing the build process to make it more universal.

So far I was able to build your project with the `sed` commands before:

```shell
user@host:/workspace/jose-3.11.5$ sed -i -e "s/-i ''/-i/g" package.json
user@host:/workspace/jose-3.11.5$ sed -i -e "s/gcp/cp/g" package.json
user@host:/workspace/jose-3.11.5$ npm run build-all
[...] # build successful
```

If you can explain the goal of the command `run-s runtime-browser lint 'build -- -p ./tsconfig/browser.json'`, I can try to reproduce it by another command or set of commands.

**Comment by panva** [comment]
If you're able to run build-all then you're done, aren't you?

npm run test
npm run test-cryptokey
npm run test-webcrypto

and if you have env variables for browserstack npm run test-browser

**Comment by babelouest** [comment]
> If you're able to run build-all then you're done, aren't you?

Well, it's a start, for sure :)

Now I try to get rid of the tools that are not exactly used for transpiling and packaging the code, like run-s, to see how the packaging works, and reproduce it with less dependencies if possible.

**Comment by babelouest** [comment]
By the way, the tests fail if I run the command:

```shell
$ npm run test
> jose@3.11.5 test /home/nico/workspace/node-jose/jose-3.11.5
> npm run-script test-cjs && ava

> jose@3.11.5 test-cjs /home/nico/workspace/node-jose/jose-3.11.5
> rm -rf test/cjs && find test -type f -name '*.mjs' -print0 | xargs -0 npx esbuild --log-level=warning --target=esnext --outdir=test/cjs --format=cjs


Error: Not supported
    at Object.<anonymous> (/home/nico/workspace/node-jose/jose-3.11.5/test/cjs/jwe/compact.decrypt.test.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nico/workspace/node-jose/jose-3.11.5/node_modules/ava/lib/worker/dependency-tracker.js:42:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at load (/home/nico/workspace/node-jose/jose-3.11.5/node_modules/ava/lib/worker/subprocess.js:213:10)
[...]
  ✖ No tests found in test/jwe/compact.encrypt.test.mjs, make sure to import "ava" at the top of your test file
  ✖ No tests found in test/jwe/cookbook.test.mjs, make sure to import "ava" at the top of your test file
  ✖ No tests found in test/jwe/compact.decrypt.test.mjs, make sure to import "ava" at the top of your test file
  ✖ No tests found in test/jwe/flattened.decrypt.test.mjs, make sure to import "ava" at the top of your test file
  ✖ No tests found in test/jwe/flattened.encrypt.test.mjs, make sure to import "ava" at the top of your test file
[...]
  cjs › jwe › compact.decrypt › failed to import

  test/cjs/jwe/compact.decrypt.test.js:35

   34:     console.error(err);
   35:     t.fail();          
   36:   });                  

  Test failed via `t.fail()`

  › test/cjs/jwe/compact.decrypt.test.js:35:7
[...]
  ✖ Internal error when running test/jwe/cookbook.test.mjs
  Error: ECMAScript Modules are not supported in this Node.js version.
  Error: ECMAScript Modules are not supported in this Node.js version.
      at load (/home/nico/workspace/node-jose/jose-3.11.5/node_modules/ava/lib/worker/subprocess.js:201:91)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  33 tests failed
```

**Comment by panva** [comment]
Well, check the node required runtime versions.

**Comment by babelouest** [comment]
Using npm 7.5.2 and nodejs v12.21.0 on a Debian unstable, I have the following result:

`npm run build-all`: success

`npm run test`: All 688 tests passed

`npm run test-cryptokey`: 22 tests failed

the error logs look like this:

```shell
SyntaxError: Unexpected token '='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at link (internal/modules/esm/module_job.js:42:21)
[...]
  jwe › smoke.mjs › failed to import

  Test failed via `t.fail()`

  › file://test/jwe/smoke.test.mjs:358:9
```

`npm run test-webcrypto`: 54 tests failed

the error logs look like this:

```shell
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
[...]
  jwe › compact.decrypt.mjs › failed to import

  Test failed via `t.fail()`

  › file://test/jwe/compact.decrypt.test.mjs:21:9
```

**Comment by panva** [comment]
cryptokey and webcrypto require node >=15, you can see that in test.yml

**Comment by babelouest** [comment]
Using current nodejs release 15.14.0 downloaded from nodejs.org, I still have errors when running the webcrypto and cryptokey tests on a Debian unstable running inside a docker instance:

```shell
$ npm run test-webcrypto
  622 tests passed
  66 known failures

$ npm run test-cryptokey
  622 tests passed
  66 known failures
```

**Comment by panva** [comment]
Those are known failures due, not errors. Your build works as expected.
