### ISSUE TITLE
Module not found: Can't resolve 'jose/jwt/sign'

### ISSUE THREAD

**Issue by qikevinjkw** [panva/jose#193]
**Describe the bug**

**To Reproduce**
1. npm install jose
2. Try to import like so: import { SignJWT } from "jose/jwt/sign";
3. Typescript compiler errors: Module not found: Can't resolve 'jose/jwt/sign'

Code to reproduce the behaviour: https://stackblitz.com/edit/react-ts-kkyw3y

**Expected behaviour**
Should import correctly with no errors

**Environment:**

- `jose` version: v3.11.6
- affected runtime is: Node.js 14.15.0
- other relevant library versions: typescript@4.2.4

**Comment by panva** [comment]
jose version: v3.11.6
affected runtime is: Node.js 14.15.0

works 🎉 

```
❯ node -v
v14.15.0

~/repo/provider ciba
❯ node -e 'import {SignJWT} from "jose/jwt/sign";console.log(SignJWT)' --input-type=module
[class SignJWT extends ProduceJWT]
```

I am unable to provide guidance on non-standard loaders or ecosystems that are not up to date with node's module resolution.

**Comment by tellnes** [comment]
I'm solving this problem by importing the relevant files directly. I put this into an intermediate file `jose.ts` and can then import like I expect to from that. Eg. like this:

```ts
import type * as T_SignJWT from 'jose/dist/types/jwt/sign'
export const { default: SignJWT } = require('jose/dist/node/cjs/jwt/sign') as typeof T_SignJWT

import type * as T_jwtVerify from 'jose/dist/types/jwt/verify'
export const { default: jwtVerify } = require('jose/dist/node/cjs/jwt/verify') as typeof T_jwtVerify
```

And then I can use it like this:
```ts
import { SignJWT } from './jose'
```

Yes I know I'm relying on internals here, but if it breaks, I can quickly fix it by editing one file on my end.

**Comment by robations** [comment]
In my experience, this can be caused by a missing "main" key in the package.json file, which is see is missing in 3.11.6.

But also, the paths in the documentation don't exist, so I don't see how the import would ever work as documented:

https://unpkg.com/browse/jose@3.11.6/

```js
> var {jwtVerify} = require("jose/jwt/verify");
// Thrown:
{ Error: Cannot find module 'jose/jwt/verify'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
```

Obviously there is no JS module at node_modules/jose/jwt/verify.js or node_modules/jose/jwt/verify/index.js. Only in the dist directory.

Am I missing something here?

**Comment by panva** [comment]
> In my experience, this can be caused by a missing "main"

There's no "main" entry because there's no "main" package or export. It's just submodules, using a node loader feature present in the supported runtimes. Tooling is slowly catching up, but is just not quite there yet.

> Am I missing something here?

https://nodejs.org/api/packages.html#packages_subpath_exports
https://nodejs.org/api/packages.html#packages_conditional_exports

**Comment by robations** [comment]
> Well, clearly they do - there are plenty of consumers of this package

Yes, that's why I thought I was missing something...

Taking a look at the "exports" docs now, I've somehow not come across this before. I'm still on nodejs 10 so I might need to use @tellnes's workaround for now.

Thanks for the quick reply.

**Comment by panva** [comment]
Well, node 10 is not a supported runtime.

**Comment by panva** [comment]
I'm aware of the `engines` field, but this is a universal package. Not sure how other runtimes would be affected.

**Comment by robations** [comment]
I see what you mean (eg installing with nodejs, but intended use for browser), but it's only advisory unless you use `engine-strict`:

> Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

And this would allow me to continue using it until I get my stupid projects tested/updated with 12+...

But I only make a suggestion.

**Comment by panva** [comment]
> And this would allow me to continue using it until I get my stupid projects tested/updated with 12+...

Can you elaborate, I'm afraid I don't quite follow.

**Comment by robations** [comment]
Sorry, ignore that sentence. I thought I had tested the functionality I needed working with nodejs 10, but I was still using 12.

```
// with nodejs 10
> var {jwtVerify} = require("jose/dist/node/cjs/jwt/verify");
Thrown:
ReferenceError: TextEncoder is not defined
```

Because of `crypto` requirements, as you stated.

**Comment by a7madgamal** [comment]
I have this error in a standard create-react-app typescript setup. I think this should be re-opened and investigated.
if we need to take care of something maybe the fix is just adding some guidance on the read.me file.

**Comment by fnagel** [comment]
Same issue here when using the package with a vue-cli setup: 

```
 ERROR  Failed to compile with 1 error                                                                                                                                                                                          11:30:12

This dependency was not found:

* jose/jwt/verify in ./src/service/license.ts

To install it, you can run: npm install --save jose/jwt/verify
No type errors found
Version: typescript 4.3.2
```

Using node v14.17.0

**Comment by panva** [comment]
typescript support for the node's ESM module loader is in the works - https://github.com/microsoft/TypeScript/pull/44501

**Comment by alanszp** [comment]
To bypass this problem with typescript, I added a alias path to the typescript config:

``` json
{
  "compilerOptions": {
    "paths": {
      "jose/jwt/*": ["node_modules/jose/dist/browser/jwt/*"]
    }
  }
}

```

**Comment by dalegacusan** [comment]
Any updates on this one? I'm getting the same error with create-react-app typescript.

**Comment by panva** [comment]
@dalegacusan you're barking up the wrong tree - this is to be solved in your tooling, not here.

**Comment by panva** [comment]
FWIW `create-react-app` still uses [`react-scripts`](https://www.npmjs.com/package/react-scripts) that utilize webpack 4, as soon as a release with webpack 5 (worked on in https://github.com/facebook/create-react-app/pull/11201) is done you'll notice "updates".

**Comment by robcresswell** [comment]
Does anyone have this working with a "current" TypeScript / Node setup (i.e. not yet using ESM, because its somewhat of a struggle with the rest of the TS ecosystem)

I think the only fix I can see is to manually hack around the existing type definitions as in https://github.com/panva/jose/issues/193#issuecomment-831139460

This is mildly disappointing because the library author seems to have made an effort to ship / maintain typedefs, but they're not usable in a Node setup from what I can see so far. Happy to be corrected 😄

**Comment by panva** [comment]
@robcresswell I really don't follow the struggles here anymore. Not only was I able to make almost anything I wanted work https://github.com/panva/it-should-just-work, but there's [TS 4.5 on the horizon](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs) with full fledged support now.

**Comment by robcresswell** [comment]
@panva Damn, sorry for wasting your time, had tried to be diligent. Thanks for working with me, that was helpful.
