### ISSUE TITLE
Private key from generated key pair cannot be converted to JWK in browser runtime

### ISSUE THREAD

**Issue by NSeydoux** [panva/jose#196]
When using `generateKeyPair` to generate a keypair in a browser runtime, using `fromKeyLike` to convert the generated private key into a JWK fails with the following error: `TypeError: non-extractable key cannot be extracted as a JWK`. 

Note that this behaviour is allowed in a node runtime.

**To Reproduce**

In a browser runtime:
- Generate a key pair with `generateKeyPair` (the algorithm is irrelevant)
- Convert the obtained private key (in `KeyLike` form) to a JWK with `fromKeyLike`

Code to reproduce the behaviour:

```
import { generateKeyPair } from 'jose/util/generate_key_pair'
import { fromKeyLike } from 'jose/jwk/from_key_like'

// In an async function
const {publicKey, privateKey} = await generateKeyPair('PS256');
const publicJwk = await fromKeyLike(publicKey);
const privateJwk = await fromKeyLike(privateKey);
```
produces the expected behaviour in NodeJS, but it throws the error described above in the browser. If need be, I can provide a larger code snippet with more context, but I set it up with `create-next-app` to get bundling and all running.

**Expected behaviour**

`privateJwk` contains a JWK object. 

**Environment:**

- `jose` version: `3.11.6`
- affected runtime is: Firefox 88.0.1 and Chrome 90.0.4430.93. No issue with NodeJS 12, 14 or 16.
- other relevant library versions:
  - NextJS 10.2.0 (for the code snippet running with Next)
  - Webpack 5.37.0

**Additional context**

I'm not 100% sure this is a bug. I think it may come from [the browser `generate.ts` implementation](https://github.com/panva/jose/blob/26bdb732a54fcc7c60554290594a04cbef7c2d40/src/runtime/browser/generate.ts#L119): the problem does not manifest if the second parameter to `crypto.subtle.generateKey` is `true`. What is the rationale for setting it to `false` ?

- [X] the bug is happening on latest `jose` too.
- [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by NSeydoux** [comment]
Well after some digging around, it turns out it isn't necessary to me, and it was a bug in my code: I had an interface waiting for two JWKs to generate a DPoP token, but the private key was actually parsed back to a KeyLike, so I'll just have not to export it in the first place. Thanks for replying so fast, and sorry for the inconvenience. Documenting the behaviour would be a nice touch, but it sounds like a good default.

**Comment by panva** [comment]
Ye. For DPoP you don't want your private key to be extractable. That's kinda the point. See https://murmuring-journey-60982.herokuapp.com/
