### ISSUE TITLE
util.promisify not being passed function? not sure if this is an issue with this codebase or dependency that uses it

### ISSUE THREAD

**Issue by pfinazzo** [panva/jose#204]
**Describe the bug**

Seems like there is a spot where `util.promisify` is being passed something that isn't a function. Will provide screenshots of error. Honestly not sure if this is an issue with another package that uses this package or if its coming directly from this package but hopefully the error Im experiencing should help clear that up!
   

**To Reproduce**
Honestly this part is hard to say. I am having this issue come up without having installed this package myself so my guess is that one of the packages I am using (I'm guessing `jsonwebtoken`) has this package somewhere in its chain of dependencies. I am getting this error when deploying to a heroku server but the issue does not happen in my local environment. It only causes my heroku app to crash. I wish I could provide more context but the log files heroku says are present are impossible to read because I cannot go into a crashed heroku server via heroku ps:exec like I normally would`

**Expected behaviour**
For it to not cause my server to crash

**Environment:**
Seeing as this environment is a heroku server, and I cannot recreate the issue when running my server locally, I actually do not know much about the runtime but I will provide my package.json as well as a screenshot of the error. I apologize for the lack of clarity here, but because this is likely a dependency that was installed from a chain of other dependencies its very hard to understand where it's coming from. Any help would be greatly appreciated! If you feel this issue was raised without enough information to tackle this issue I would understand that! I wish I could provide more context but frankily heroku hides so much of the complexity

What I can provide is that the node version is `v10.6.0`

**Additional context**
![Screen Shot 2021-05-24 at 6 01 22 PM](https://user-images.githubusercontent.com/29343873/119424314-0fcd8c00-bcba-11eb-95dc-fe1628fc1bf4.png)
![Screen Shot 2021-05-24 at 6 01 57 PM](https://user-images.githubusercontent.com/29343873/119424360-2542b600-bcba-11eb-9917-385ad1106ab3.png)

**Comment by panva** [comment]
All I can say is that node v10.6.0 is not a supported runtime of either of the semver major versions of this package.
