### ISSUE TITLE
invalid key input

### ISSUE THREAD

**Issue by rifton007** [panva/jose#212]
**Describe the bug**

I just try to reproduce the example of documentation [JSON Web Tokens (JWT)Signing](https://github.com/panva/jose/blob/main/docs/classes/jwt_sign.signjwt.md#readme)
It returns `TypeError: invalid key input`

**To Reproduce**

Code to reproduce the behaviour:

```js
const secret = 'bGoa+V7g/yqDXvKRqq+JTFn4uQZbPiQJo4pf9RzJ'

const accessToken = await new SignJWT({ 'urn:example:claim': true })
	.setProtectedHeader({ alg: 'ES256' })
	.setIssuedAt()
	.setIssuer('urn:example:issuer')
	.setAudience('urn:example:audience')
	.setExpirationTime('2h')
	.sign(secret)
```

**Expected behaviour**
Create a simple JWT for authentification.

**Environment:**
- `jose` version: 3.12.3
- affected runtime is: Node.js 14.17.0, 
- [ X ] the bug is happening on latest `jose` too.
- [ X ] i have searched `invalid key input` the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Please see the docs on what type the key should be.

**Comment by rifton007** [comment]
Since 5 days ago that I try again and again. The code above is just a **copy/paste** from our documentation, but does not working for me. I read everything of your documentation :

- https://github.com/panva/jose/blob/main/docs/classes/jwt_sign.signjwt.md#readme
- https://github.com/panva/jose/blob/main/docs/functions/jwt_verify.jwtverify.md#readme
- https://github.com/panva/jose/issues/210
- https://github.com/panva/jose/issues/114

Thank you

**Comment by panva** [comment]
> > Please see the docs on what type the key should be.
>
> Since 5 days ago that I try again and again.

Documentation has all the information what the `key` argument type should be.

<img width="596" alt="Screenshot 2021-06-23 at 13 32 12" src="https://user-images.githubusercontent.com/241506/123089734-9dbaa500-d427-11eb-99a3-052aff26fc42.png">

<img width="1041" alt="Screenshot 2021-06-23 at 13 32 23" src="https://user-images.githubusercontent.com/241506/123089731-9bf0e180-d427-11eb-9ef8-b9865757dddf.png">

**Comment by jvanalst** [comment]
To be honest, I also found these new crypto libraries confusing. While I agree that people should read the documentation, if you've never seen SubtleCrypto or crypto.createPublicKey before clicking into one of the links isn't super helpful (especially for SubtleCrypto with all it's numerous options that aren't particularly well explained because you need to have a detailed knowledge of cryptography first).

It also doesn't help the jsonwebtoken (the JWT library I'm trying to migrate from) just accepts a string with proper headers, so all you need to do is read your public key file into memory and away you go.

It would definitely be helpful to add a few more concrete examples somewhere.... actually... maybe that's exactly what we need? A migration guide from jsonwebtoken to jose?

```javascript
jwt = require('jsonwebtoken');
qs = event.queryStringParameters;
const payload = jwt.verify(
  qs.jwt,
  fs.readFileSync('./mykey.pub'), //Standard PEM-format public key (see below)
  { algorithms: ['RS256'] },
);
```

vs.

```javascript
const { jwtVerify } = require('jose/jwt/verify');
qs = event.queryStringParameters;
const { payload } = await jwtVerify(
  qs.jwt,
   crypto.createPublicKey(fs.readFileSync('./mykey.pub')),
   { algorithms: ['RS256'] },
 );
 ```
 
 mykey.pub:
 ```
 -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzY0f0nZTXRmRYYNuXnRr
23MFM90KbuW9iwF4zUziroEf3106Bq6o+QYMT6XaAEuxGPiwSsTw5nqiKLVg3aBf
xTkJ5fsm5UkTRs5MIUan1Pzwr8e0iwXtgjVtmiXjP4bDJ57dR69LvidiuXsvXn4U
c6yAuyWEzpbceB/NTBzkECJqWRAo1/nFB3xQz8Hs/Tgv4nrjkwzDAJdMAO7ODmzx
cnVQXuxiBffFCcQaXXcf2iPs+Ot57L2cLnCyDendKtXmPN0ix2W6gzBTNLxAZmEE
KEn16dnUsp83lwsUkoreOp5IYdbHo7BPDT6NEjzI5GicKRX3yyfyyIDvp1IN+9T7
+wIDAQAB
-----END PUBLIC KEY-----
```

**Comment by panva** [comment]
@jvanalst please update/remove those samples before anyone copy/pastes readFileSync to their code... you know that's gonna happen.
