### ISSUE TITLE
bug: Unexpected character '#' on build

### ISSUE THREAD

**Issue by rendall** [panva/jose#23]
**Describe the bug**

Bundling via `webpack` (via `netlify-lambda`) fails with the following error:

```
ERROR in ../node_modules/@panva/jose/lib/jws/sign.js 14:2
Module parse failed: Unexpected character '#' (14:2)
```
(Detailed stack trace at the end of this post.)

It appears that webpack barfs at this kind of syntax with the `#`

```
class Sign {
  #b64
  #payload
  #recipients
  ...
```

I'm submitting an issue here because '#' appears to be invalid syntax.

**To Reproduce**

Steps to reproduce the behaviour:

1.  `git clone https://github.com/rendall/jwt-implementation/tree/%40panva/jose`
1. `cd ./jwt*` or otherwise into project directory
1.  `npm / yarn install`
1.  `npm / yarn run build`

**Expected behaviour**

That there be no `Unexpected character` error.

**Environment:**
 - @panva/jose version: `1.0.0`
 - node version: `v12.0.0`

**Additional context**

 - [x] the bug is happening on latest @panva/jose too.
 - [ ] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

Detailed Error stack trace
```
netlify-lambda: Building functions
Hash: c3ac99528bc9843d63e5
Version: webpack 4.30.0
Time: 2110ms
Built at: 04/27/2019 7:55:37 AM
  Asset     Size  Chunks  Chunk Names
auth.js  124 KiB       0  auth
Entrypoint auth = auth.js
 [0] external "crypto" 42 bytes {0} [built]
 [2] ../node_modules/@panva/jose/lib/errors.js 275 bytes {0} [built] [failed] [1 error]
 [5] ../node_modules/@panva/jose/lib/jwk/key/base.js 5.89 KiB {0} [built]
[10] ../node_modules/@panva/jose/lib/jwks/keystore.js 202 bytes {0} [built] [failed] [1 error]
[16] ../node_modules/@panva/jose/lib/jwk/generate.js 1.5 KiB {0} [built]
[18] ../node_modules/@panva/jose/lib/jws/index.js 525 bytes {0} [built]
[31] ../node_modules/@panva/jose/lib/jwk/index.js 298 bytes {0} [built]
[37] ../node_modules/@panva/jose/lib/index.js 178 bytes {0} [built]
[38] ../node_modules/dotenv/lib/main.js 2.87 KiB {0} [built]
[39] ./auth.js 3.21 KiB {0} [built]
[40] ../node_modules/@panva/jose/lib/jwe/index.js 570 bytes {0} [built]
[85] ../node_modules/@panva/jose/lib/jwks/index.js 70 bytes {0} [built]
[89] ../node_modules/@panva/jose/lib/jwt/index.js 150 bytes {0} [built]
[92] external "fs" 42 bytes {0} [built]
[93] external "path" 42 bytes {0} [built]
    + 79 hidden modules

ERROR in ../node_modules/@panva/jose/lib/jws/sign.js 14:2
Module parse failed: Unexpected character '#' (14:2)
You may need an appropriate loader to handle this file type.
|
| class Sign {
>   #b64
|   #payload
|   #recipients
 @ ../node_modules/@panva/jose/lib/jws/index.js 1:13-30
 @ ../node_modules/@panva/jose/lib/index.js
 @ ./auth.js
```

**Comment by panva** [comment]
This module is only for node.js runtime due to its usage of the crypto module’s new features.

https://github.com/panva/jose/blob/master/README.md#how-do-i-use-it-outside-of-nodejs

+plus it seems the tools like webpack aren’t ready for [private instance javascript fields](https://github.com/tc39/proposal-class-fields/blob/master/README.md) shipped with node 12’s V8 version.

**Comment by panva** [comment]
duplicate of #22 in the end.

**Comment by rendall** [comment]
This is a Node application.

**Comment by panva** [comment]
Then don't transpile `@panva/jose` dependency until your tooling is ready to recognize the new syntax.

**Comment by panva** [comment]
#37 https://v8.dev/features/class-fields

**Comment by panva** [comment]
I've made @panva/jose compatible with lts/dubnium, it is now being tested with Node.js `^10.13.0 || >=12.0.0` and Electron `^6.0.0`

It is not without caveats, but they are acceptable.
- Importing X.509 certificates and handling x5c is only supported when Node.js >= 12.0.0 runtime is detected
- OKP keys are only supported when Node.js >= 12.0.0 runtime is detected

**Comment by rendall** [comment]
Brilliant!  Thanks.

**Comment by panva** [comment]
A quick note, i've release a new major (v3.x) which is now a universal module with 0 dependencies and now works the same in the browser (using webpack 5 with no issues) as well as node.
