### ISSUE TITLE
bug: KeyStore.toJWKS() doesn't exist in TS typings

### ISSUE THREAD

**Issue by thomasvargiu** [panva/jose#25]
`KeyStore.toJWKS()` method doesn't exist in TS typings.

**Example code:** 
```ts
import { JWKS } from '@panva/jose';
const { KeyStore } = JWKS;
const keystore = new KeyStore();

keystore.toJWKS(true);
```

**Environment:**
 - @panva/jose version: v1.0.1
 - node version: v12.0.0

**Comment by panva** [comment]
@thomasvargiu good catch, can you open a PR?

**Comment by thomasvargiu** [comment]
@panva you're faster than me! :)
