### ISSUE TITLE
Problem mocking jwks URL with nock

### ISSUE THREAD

**Issue by nflaig** [panva/jose#259]
### What happened?

I am using `createRemoteJWKSet` inside a module which is used by multiple nodejs services. When running tests in the services the jwks endpoint is mocked using `nock`. The issue I am facing right now is that the jwks endpoint mock does not work because `jose` is caching the `http/https` module (see [here](https://github.com/panva/jose/blob/main/src/runtime/node/fetch_jwks.ts#L11)). A workaround is to ensure that `nock` is required before `fetch_jwks` (e.g. by adding nock to require in mocharc file) which is hard to ensure because my module which is using `jose` internally is used by different teams/developers.

An easy fix would be to initialize the `protocols` variable inside the `fetchJwks` function.

### Version

3.14.3

### Runtime

Node.js

### Runtime Details

v14.17.3

### Code to reproduce

```js
// code in module which is used by multiple services
import { createRemoteJWKSet } from "jose/jwks/remote";

const getKeyFromJwks = createRemoteJWKSet(new URL(`${services.auth.baseUrl}/keys`), {
    cooldownDuration: jwksFetchCooldownDuration
});

// mock to be used by services in before hook during testing
import nock from "nock";

nock(services.auth.baseUrl).persist().get("/keys").reply(200, jwks)
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
> An easy fix would be to initialize the `protocols` variable inside the `fetchJwks` function.

That would kinda defeat the point of doing it in the first place.

It is common that mocks need to be required first, I suggest you ensure that happens in your case as well. Or better yet, don't nock the http response but rather mock the return of the get key function.

**Comment by panva** [comment]
I've come around on this having encountered a case where it was unclear why nock didn't work despite being required upfront. I'll refactor the code to remove this obstacle.
