### ISSUE TITLE
Optional integrity check in Crit headers on JWTVerify

### ISSUE THREAD

**Issue by ruiengana** [panva/jose#273]
### What happened?

JOSE is returning  ```JWSInvalid: Extension Header Parameter "<crit parameter>" is missing``` even when crit parameter is set false to ignore integrity check as per documentation https://github.com/panva/jose/blob/main/docs/interfaces/jwt_verify.JWTVerifyOptions.md#crit

### Version

3.19.0

### Runtime

Node.js

### Runtime Details

v14.16.0

### Code to reproduce

// shoudn't fail with protected header as { alg: 'HS256', crit: ['nope'] } and JWT Verity Options as { crit: {'nope': false} }

  await flattenedVerify(
        { protected, payload, signature},
        publicKeyObject,
        {
          crit: {
            'nope': false,
          },
        },
      );
    }
```


### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
@ruiengana where does it say it makes the extension header optional?

**Comment by panva** [comment]
I think I understand the gist of your report. Nevertheless, everything is working as intended and indeed as well as documented.

"crit" JOSE Header Parameter as shown above (sourced in JWT case just from the Protected Header as other JOSE Header parameter sources are not used by the compact serialization) is syntactically incorrect. All crit header parameter members must be present in the JOSE Header.

https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.11

> Its value is an array listing the Header Parameter names present in the JOSE Header that use those extensions.

**Comment by ruiengana** [comment]
Hi @panva,

apologies, here you go.

```
import { compactVerify } from 'jose/jws/compact/verify'

(async () => {
    const secret = new TextEncoder().encode('FxYQYpLnYGnAV29ZRn9YtseqQqM64qWtvg36dwVvfmHDAzbGkJZA2qB4dyHyFm4SwGtXksSGz4sV57TNyMYM4tbhbCuRKxZvLHDEvbhjrgr6gkRbqTYznajSZuBZD2AAuKGLxgKaJaasaPyEsAnws9mx4hTu2tvF9qRbddxM5mfxRGwjtXMBccURffbfCmf9wZHNMu7DEGQ3NLJKFXLmW4zrdfQypgBZ7t4fK648L4C4eYLr9MzHSD7Wvz4nLM7S');
    const jws = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImNyaXQiOlsiY2xhaW0iXX0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.9j0YRAhxhuo5s1FtWjGKTtaW0WJ856DRF1ztSDcjcwM";
    await compactVerify(jws, secret,  { crit: { 'claim': false } });
})();
```
``

**Comment by panva** [comment]
Yes you are. Allowing a critical header parameter not to be integrity protected is not the same as allowing it to be missing when signalled by the crit header itself.
