### ISSUE TITLE
question: Typescript?

### ISSUE THREAD

**Issue by connorsmallman** [panva/jose#28]
Is this Typescript?  https://github.com/panva/jose/blob/master/lib/jwe/encrypt.js#L21

**Comment by connorsmallman** [comment]
https://github.com/panva/jose/issues/23 - related, closing issue

**Comment by panva** [comment]
Nope, it's regular new ECMAScript available in Node 12 which is required primarily for its `crypto` API improvements, using private class fields is just something available to me as a side-effect of needing node 12 for its new APIs.

**Comment by connorsmallman** [comment]
@panva thanks for the reply. I've had a similar issue as https://github.com/panva/jose/issues/23 because we're using Node LTS.

**Comment by panva** [comment]
> <img width="908" alt="Screenshot 2019-06-19 18 01 02" src="https://user-images.githubusercontent.com/241506/59781523-41629f00-92bc-11e9-9af4-2f0a33e7d63c.png">
> <img width="882" alt="Screenshot 2019-06-19 18 01 10" src="https://user-images.githubusercontent.com/241506/59781526-4293cc00-92bc-11e9-80f5-db848c7e1829.png">
> https://github.com/panva/jose/blob/v1.2.0/package.json#L62-L64

I just don't know how to make it more prominent and clear :)

**Comment by connorsmallman** [comment]
@panva agreed but I don't use this module directly openid-client does and I was updating it.

**Comment by panva** [comment]
Same story. It’s right there in the readme in bold with a pointer to v2 which is still ok to use and declared in package.json

**Comment by connorsmallman** [comment]
I admit I was too quick to open an issue and not read what was in front of me. Thanks for the help!

**Comment by panva** [comment]
You're welcome!
