### ISSUE TITLE
{err package_path_not_exported} 

### ISSUE THREAD

**Issue by zaourzag** [panva/jose#288]
### What happened?

there are missing files in the export mainly:
 "./dist/node/cjs/jwt/sign": "./dist/node/cjs/jwt/sign.js",
    "./dist/node/cjs/jwt/verify": "./dist/node/cjs/jwt/verify.js",

### Version

3.5.0

### Runtime

Node.js

### Runtime Details

14.17.6

### Code to reproduce

```js
import SignJWT from 'jose/dist/node/cjs/jwt/sign'
import VerifyJWT from 'jose/dist/node/cjs/jwt/verify'
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please see the documentation for those modules. Preferably tho, upgrade to v4.x

**Comment by zaourzag** [comment]
This still happens in the newest release,

**Comment by panva** [comment]
Where in the docs does it say modules are required from a `dist` folder?

**Comment by panva** [comment]
On v4.x

```js
import { SignJWT, jwtVerify } from 'jose'
```
