### ISSUE TITLE
SignJWT.sign(<Uint8Array>) returns `<rejected> TypeError`

### ISSUE THREAD

**Issue by roseMix** [panva/jose#290]
### What happened?

I was attempting to sign JWT with a `Uint8Array`. `sign()` method is supposed to allow Uint8Array as per: https://github.com/panva/jose/blob/v4.0.4/docs/classes/jwt_sign.SignJWT.md#sign

But it returned: 
```
Promise {
  <rejected> TypeError: Key must be of type CryptoKey. Received an instance of Uint8Array
    at asymmetricTypeCheck (https://deno.land/x/jose@v4.0.4/lib/check_key_type.ts:20:11)
    at checkKeyType (https://deno.land/x/jose@v4.0.4/lib/check_key_type.ts:70:5)
    at FlattenedSign.sign (https://deno.land/x/jose@v4.0.4/jws/flattened/sign.ts:130:5)
    at CompactSign.sign (https://deno.land/x/jose@v4.0.4/jws/compact/sign.ts:60:39)
    at SignJWT.sign (https://deno.land/x/jose@v4.0.4/jwt/sign.ts:67:16)
    at <anonymous>:2:5
}
```

### Version

v4.0.4

### Runtime

Deno

### Runtime Details

1.13.0

### Code to reproduce

```js
import { SignJWT } from 'https://deno.land/x/jose@v4.0.4/index.ts'

// Returns Uint8Array
const privKey = await Deno.readFile("private-key.pem")

const jwt = await new SignJWT({}).setProtectedHeader({ alg: 'ES256' }).sign(privKey)
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
v1.18.0 mostly completes the implementation of Web Cryptography API, the above will now work as expected given you import the key using the import key functions.
