### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by rom1504** [panva/jose#307]
### What happened?

While trying to use jose (there https://github.com/PrismarineJS/prismarine-auth/blob/27b324544cacf518023381fe00705c919a95bf4a/src/TokenManagers/XboxTokenManager.js#L8)

we get a `ReferenceError: TextEncoder is not defined`

See https://github.com/PrismarineJS/node-minecraft-packets/runs/4087042559?check_suite_focus=true

### Version

4.1.4

### Runtime

Node.js

### Runtime Details

node v14.15.1

### Code to reproduce

Running this kind of code https://github.com/PrismarineJS/prismarine-auth/blob/27b324544cacf518023381fe00705c919a95bf4a/src/TokenManagers/XboxTokenManager.js#L22
in a jest test

see https://github.com/PrismarineJS/prismarine-auth/issues/10#issuecomment-943371074

I don't completely get the relationship between jest and jose, but this doesn't seem to be fully fixed

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
That project is using jest 26, jest 26 default testEnvironment is `jsdom`. Either upgrade to jest 27, or explicitly use the `node` testEnvironment.

> but this doesn't seem to be fully fixed

I can't fix people's tendency to use a frontend oriented test runner for node code. Jest is a horrible node test runner, it messes up with globals and doesn't use native node's module resolution. It is not representative of the actual environment your code will run in.

**Comment by rom1504** [comment]
thanks, will update to jest 27!

**Comment by panva** [comment]
> thanks, will update to jest 27!

Well, it's just that the default `testEnvironment` changed from `jsdom` to `node` in 27.

**Comment by holylovelqq** [comment]
@panva is there any solutions with `testEnvironment : jsdom `? 
in my project, if i change the `testEnvironment` to `node`, all test will be error.

**Comment by panva** [comment]
> @panva is there any solution with `testEnvironment : jsdom `? in my project, if i change the `testEnvironment` to `node`, all tests will be error.

I'm not going to invest time in solving jsdom/jest issues not introduced here. See https://github.com/jsdom/jsdom/issues/2524 for possibly finding a workaround.
