### ISSUE TITLE
Raising error always when trying to decrypt compact JWE

### ISSUE THREAD

**Issue by r-priyam** [panva/jose#314]
### What happened?

While using `Python` backend to encrypt a string to get compact JWE string and then trying to decrypt it with `jose` it's raising error.

Full traceback -
```
C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\lib\check_key_type.js:9
        throw new TypeError((0, invalid_key_input_js_1.default)(key, ...is_key_like_js_1.types, 'Uint8Array'));
              ^

TypeError: Key must be one of type KeyObject, CryptoKey, or Uint8Array.
    at symmetricTypeCheck (C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\lib\check_key_type.js:9:15)
    at checkKeyType (C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\lib\check_key_type.js:41:9)
    at decryptKeyManagement (C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\lib\decrypt_key_management.js:15:37)
    at flattenedDecrypt (C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\jwe\flattened\decrypt.js:101:61)
    at compactDecrypt (C:\Users\Priyam\Documents\test\node_modules\jose\dist\node\cjs\jwe\compact\decrypt.js:18:63)
    at Object.<anonymous> (C:\Users\Priyam\Documents\test\index.js:4:40)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```
Python code -
```py
>>> from jose import jwe
>>> jwe.encrypt('Hello, World!', 'asecret128bitkey', algorithm='dir', encryption='A128GCM')
'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIn0..McILMB3dYsNJSuhcDzQshA.OfX9H_mcUpHDeRM4IA.CcnTWqaqxNsjT4eCaUABSg'
```
Doc ref - >>> from jose import jwe
>>> jwe.encrypt('Hello, World!', 'asecret128bitkey', algorithm='dir', encryption='A128GCM')
'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIn0..McILMB3dYsNJSuhcDzQshA.OfX9H_mcUpHDeRM4IA.CcnTWqaqxNsjT4eCaUABSg'

### Version

4.1.4

### Runtime

Node.js

### Runtime Details

Node - 16.13.10

### Code to reproduce

```js
const { compactDecrypt } = require('jose')
const decoder = new TextDecoder()
const jwe = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIn0..McILMB3dYsNJSuhcDzQshA.OfX9H_mcUpHDeRM4IA.CcnTWqaqxNsjT4eCaUABSg'
const { plaintext, protectedHeader } = compactDecrypt(jwe, 'asecret128bitkey')

console.log(protectedHeader)
console.log(decoder.decode(plaintext))
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
@r-priyam pass your secret key as a Buffer or Uint8Array as per the docs.

**Comment by r-priyam** [comment]
@panva So you mean just -
```js
var enc = new TextEncoder();
compactDecrypt(jwe, enc.encode('asecret128bitkey'))
```

**Comment by panva** [comment]
If your secret is ascii/utf-8. yes. If its an actual random set of bytes eventually encoded as base64, or hex. You'd do `Buffer.from('...', 'hex')`

**Comment by panva** [comment]
The JWE you've passed is invalid tho.

https://datatracker.ietf.org/doc/html/rfc7518#section-5.3 states the that

```
   Use of an IV of size 96 bits is REQUIRED with this algorithm.
```

The IV in your token is 128 bits, instead of the required 96.

**Comment by r-priyam** [comment]
@panva 
Was just testing it from the example of repo. Here's the key that i generated and it still stucks, If you can guide please
```js
const { compactDecrypt } = require('jose')
const decoder = new TextDecoder()
const jwe = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIn0..Mf_ay7o5AbhoPIzUBHAf0Q.gPvVoADDE0whp7azdStnG35ON94mcnfXgWL8B4QFbyfz5n0F9oiqegnCKFMq2pAmfMrdS2E0yJ53viGxsziKX7KEvNEzzCZnAPYqZ2BKT1kY7SLobpU5eA79B1h8_psaxRdVXCE-12bb-Ds32PD5nq9D9fXbCjRrGKTr9pwHNyGFAzrWw_K5nB1IAwloutQUwXCX8GLkavjCSiD1VumSb59XrIPrcay7wZFkWCL8JK7GKwEc_2_X3uU9dLjpGzWM549u8iO6kDWMoRukAtgK26mEIwx_BhEsGXDpMh7OtO6VkDVZYBdLdUwkq3A7OvYbDLnleE-Z2e7tHtEwLBwrRUV6BgRaHcxjtUYEbJ36YzlCrGQi9hNUmDBFoZ-Y9D3buXJkxdLR08hEem7ds0QBdbugo4Uf6FQLP7Xh4PUq1hVd_fbVs-zX1aPcXnuI7uP_agUOzt-p9VK90mwn73ct7sw_nDExtolc_uESxXOptH4zfd91ayZjsLGRrJG60wlV1CXlBcM.ojgJx4stF85F9UKXp_AxRw'
var enc = new TextEncoder();
const { plaintext, protectedHeader } = compactDecrypt(jwe, enc.encode("k+L4PrXyYixab2sT"))

console.log(protectedHeader)
console.log(decoder.decode(plaintext))
```

**Comment by panva** [comment]
Of course it stucks, because the IV is of invalid length. The produced JWE is invalid.

**Comment by panva** [comment]
You're also missing the fact that `compactDecrypt` returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by r-priyam** [comment]
Thank you, Going to change python lib and then will let you know how it went :)

**Comment by panva** [comment]
> Thank you, Going to change python lib and then will let you know how it went :)

You should report this non-conformance to the library's authors too.
