### ISSUE TITLE
bug: jti not used during JWT.sign

### ISSUE THREAD

**Issue by alvis** [panva/jose#33]
When using JWT.sign, `jti` can be supplied as an option for it to be included in the payload.
However, `jti` is currently not included in the payload generation
see below: https://github.com/panva/jose/blob/10a1b6400de7c70dd728fe212826d8e1cf9800f2/lib/jwt/sign.js#L65-L74

**Additional context**

 - [x] the bug is happening on latest @panva/jose too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Why a bug when docs do not state that a jti is being generated? A jti is only useful when its consumers use it to e.g. endure one time use of a JWT. Not all tokens need it hence i don’t mean to provide its generation by default. 

After all, you can choose the entropy and format fitting your use case well and have all the means to push it to the payload.

**Comment by panva** [comment]
@alvis thank you, i can see the issue (after having a second look).

**Comment by alvis** [comment]
Thank you @panva ;)

**Comment by panva** [comment]
@alvis v1.4.1
