### ISSUE TITLE
Token invalid in App Store Server API with Jose

### ISSUE THREAD

**Issue by yuanpli** [panva/jose#346]
### What happened?

There is a app store server api that uses jose to sign the token. But when sends to Apple app store server, it will get 401 error.

See ticket https://github.com/agisboye/app-store-server-api/issues/2

### Version

v4.x.x

### Runtime

Node.js

### Runtime Details

npm@6.11.3

### Code to reproduce
Some sensitive data replaced with 'xxxx'

```js
       const algorithm = 'ES256'
        const pkcs8 = `-----BEGIN PRIVATE KEY-----
xxxxx
xxxxx
xxxxx
xxx
-----END PRIVATE KEY-----`
        const privateKey = await jose.importPKCS8(pkcs8, algorithm)

        const jwt = await new jose.SignJWT({
            "bid": "com.xxx.xxx",
            "nonce": "xxxxxx"
        })
            .setProtectedHeader({ alg: 'ES256', kid: 'xxxx', typ: 'JWT' })
            .setIssuedAt()
            .setIssuer('xxxx')
            .setAudience('appstoreconnect-v1')
            .setExpirationTime('1h')
            .sign(privateKey);
```

Code with `jsonwebtoken`
```
       const algorithm = 'ES256'
        let payload = {
            bid: "com.xxx.xxx",
            nonce: "xxxxx"
        };
        var token = jwt.sign(payload, pkcs8, {
            algorithm: 'ES256',
            expiresIn: '1h',
            issuer: 'xxxxx',
            audience: 'appstoreconnect-v1',
            header: {
                alg: 'ES256', kid: 'RPVD7VA7U4', typ: 'JWT'
            }
        });
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
There's no concrete steps to reproduce an issue. There's not even an issue described. 

At least try and post an actual generated token from jose and one from jsonwebtoken and a public key that can be used to verify them or be able to see the difference between tokens.

**Comment by yuanpli** [comment]
> 

- Code with jsonwebtoken

```
const algorithm = 'ES256'
        let payload = {
            bid: "com.xxx.xxx",
            nonce: "xxxxx"
        };
        var token = jwt.sign(payload, pkcs8, {
            algorithm: 'ES256',
            expiresIn: '1h',
            issuer: 'xxxxx',
            audience: 'appstoreconnect-v1',
            header: {
                alg: 'ES256', kid: 'RPVD7VA7U4', typ: 'JWT'
            }
        });
```
- token generated by jose
```
eyJhbGciOiJFUzI1NiIsImtpZCI6IlJQVkQ3VkE3VTQiLCJ0eXAiOiJKV1QifQ.eyJiaWQiOiJjb20ubW9ibGFiLmtpZHMiLCJub25jZSI6ImIwNTk5NmEzLTA0YmYtNDg2NS1iZTMyLTQ0MTY0NmRhOWUyNCIsImlhdCI6MTY0Mjk4ODQ2MywiaXNzIjoiNjlhNmRlNzctODJmMC00N2UzLWUwNTMtNWI4YzdjMTFhNGQxIiwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwiZXhwIjoxNjQyOTkyMDYzfQ.MEQCIHOq6fZxkDCb1CuroX52rMdmIbc5l9d1whytuzGBUl_RAiA_sgwrl2Hn5PulvJOHbTi40xhBBB6uYcWbJZ5B5iYYE
```
- token generated by jsonwebtoken
```
yJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJQVkQ3VkE3VTQifQ.eyJiaWQiOiJjb20ubW9ibGFiLmtpZHMiLCJub25jZSI6ImIwNTk5NmEzLTA0YmYtNDg2NS1iZTMyLTQ0MTY0NmRhOWUyNCIsImlhdCI6MTY0Mjk4ODQ2MywiZXhwIjoxNjQyOTkyMDYzLCJhdWQiOiJhcHBzdG9yZWNvbm5lY3QtdjEiLCJpc3MiOiI2OWE2ZGU3Ny04MmYwLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEifQ.UWTkAtCARR726IruPLQvqnHJ0Iw8XZclY0SFNtv-rEeRq3OtUsvKV6DKJnrMj5GEmDxQKbwDAXUPgIKjSEMh5A
```

After got the token, I will use it to post to App store server.
The following is using the token generated by jose
![image](https://user-images.githubusercontent.com/13729335/150709840-6a63fdee-1cbf-4d4f-9995-82293a27a6a2.png)

The following is using the token generated by jsonwebtoken
![image](https://user-images.githubusercontent.com/13729335/150709959-9626667c-f7c7-43d6-80b8-a276248916f6.png)

**Comment by panva** [comment]
And the public key that can be used to verify? I'm not asking for these things for no reason. 

Please post the result of crypto.createPublicKey(pkcs8).export({ format: "pem", type: "spki" })

**Comment by panva** [comment]
You're not running a supported version of Node.js, see [Node.js Support](https://github.com/panva/jose/issues/262).
