### ISSUE TITLE
RemoteJWKSetOptions durations are unitless

### ISSUE THREAD

**Issue by tv42** [panva/jose#347]
### What happened?

https://github.com/panva/jose/blob/main/docs/interfaces/jwks_remote.RemoteJWKSetOptions.md

> Duration for which no more HTTP requests will be triggered after a previous successful fetch. Default is 30000.

> Timeout for the HTTP request. When reached the request will be aborted and the verification will fail. Default is 5000.

30000 what? Milliseconds? Seconds?

### Version

current master, something past v4.3.8

### Runtime

Other (I will specify below)

### Runtime Details

n/a

### Code to reproduce

```js
https://github.com/panva/jose/blob/main/docs/interfaces/jwks_remote.RemoteJWKSetOptions.md#cooldownduration
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
It's milliseconds. Feel free to open a PR fixing this in the `src/jwks/remote.ts` source file.
