### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by josh-egan** [panva/jose#36]
**Describe the bug**

I just installed `oidc-provider` and am attempting to use it. That package has this package, `@panva/jose` as a dependency. When I attempt to run my project, I am getting this error:

```bash
Uncaught Exception! /node_modules/@panva/jose/lib/jwe/encrypt.js:21
  #aad
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

The invalid characters appear to be in the source code: https://github.com/panva/jose/blob/master/lib/jwe/encrypt.js#L21 Seems like a mistake that `#` characters ended up in the source code. However, if the `#` characters are supposed to be there, how do you recommend proceeding?

**To Reproduce**

Steps to reproduce the behaviour:

1.  `npm i oidc-provider`. 
2.  Note that `@panva/jose` version 1.6.1 was installed as a dependency. `node_modules/@panva/jose/package.json`
3.  Attempt to run your project using `oidc-provider`.
4.  Note that there is a runtime error.
5.  Look in `node_modules/@panva/jose/lib/jwe/encrypt.js` and find `#` character in many places.
6. Also note that the `#` character has been committed into the source code. https://github.com/panva/jose/blob/master/lib/jwe/encrypt.js#L21

**Expected behaviour**
I expected the code to run. :smile: 

**Environment:**
 - @panva/jose version: 1.6.1
 - node version: 10.9.0

**Additional context**

 - [x] the bug is happening on latest @panva/jose too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
This is not a bug, it's just an ES Next language not available to older node versions. You can see `oidc-provider@6.x` has a runtime requirement of node >=12.0.0 right in the readme.

**Comment by josh-egan** [comment]
Ah, I see. I hadn't seen that syntax before. Sorry for the bad issue.

**Comment by panva** [comment]
No problem.

Node >=12.0.0 is the described minimal version in both projects README's as well as package.json (so during npm/yarn install you must've omitted a warning). It is for its KeyObject and `crypto` module additions that are only available in the Node 12 trackk. This new private class fields syntax is just something which i’m glad to have available as a side effect.

**Comment by panva** [comment]
https://v8.dev/features/class-fields

**Comment by panva** [comment]
I've made @panva/jose compatible with lts/dubnium, it is now being tested with Node.js `^10.13.0 || >=12.0.0` and Electron `^6.0.0`

It is not without caveats, but they are acceptable.
- Importing X.509 certificates and handling x5c is only supported when Node.js >= 12.0.0 runtime is detected
- OKP keys are only supported when Node.js >= 12.0.0 runtime is detected

**Comment by josh-egan** [comment]
Cool, sounds great, thanks! I think supporting active LTS versions of node is a great idea. In my particular case, upgrading to node 12 wasn't a problem, so I upgraded our project to node 12.x and both `oidc-provider` and `@panva/jose` have been working great. :+1:
