### ISSUE TITLE
buffer module not supported by Cloudflare Workers

### ISSUE THREAD

**Issue by tranzium** [panva/jose#371]
### What happened?

When including Jose 4.5.1 in my Cloudflare Worker project, I am greeted with this error:
`No such module "buffer".`

Jose seems to be using a Node related API that is not supported via Cloudflare Wokers.

The issue further extends to Miniflare which does not support buffer either:
`Unable to resolve dependency "buffer": no matching module rules.`

### Version

4.5.1

### Runtime

Cloudflare Workers

### Runtime Details

wrangler 1.19.8, node 16.13.0, miniflare 2.3.0

### Code to reproduce

```js
npm i jose@latest
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
jose has a browser ready entry point declared in its package.json

if you have an issue take it up with whatever bundling stack that it does not pick up on the browser entrypoint

**Comment by panva** [comment]
Furthermore, no steps to reproduce.
