### ISSUE TITLE
Signing JWT doesn't work with symmetric secret

### ISSUE THREAD

**Issue by vladinator1000** [panva/jose#372]
### What happened?

Hi there, I got an error when I tried to sign my token for a simple webapp where I'm the only one that will verify and sign my token.

I got this error when trying to sign with a secret like
```js
const secret = new TextEncoder().encode(config.jwt.secret)
```

```
TypeError: Key must be one of type KeyObject or CryptoKey. Received an instance of Uint8Array
```

When I try with
```js
const secret = Buffer.from('hello')
```

I get this error
```
TypeError: Key must be one of type KeyObject or CryptoKey. Received an instance of Buffer
```

Here's an executable reproduction:
https://codesandbox.io/s/jose-4-5-1-jwt-signing-bug-xcqp0j?file=/src/index.js

Node version: v17.1.0

### Version

4.5.1

### Runtime

Node.js

### Runtime Details

Node, Browser and Cloudflare

### Code to reproduce

```js
import { SignJWT } from "jose";

const secret = new TextEncoder().encode("hello");

function signToken(user) {
  return new SignJWT({ user })
    .setProtectedHeader({ alg: "ES256" })
    .setIssuedAt()
    .setExpirationTime("24h")
    .sign(secret);
}

signToken({ id: 1 });
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
ES256 is an asymmetric algorithm. 

https://github.com/panva/jose/issues/210

Actually specify a symmetric one to use and you'll be good to go.
