### ISSUE TITLE
JSON Web Key Set malformed

### ISSUE THREAD

**Issue by TLKG** [panva/jose#382]
### What happened?

Try to validate a Microsoft token at backend:

```
const jose = require("jose");
const theToken = "eyJ...";   // Bearer Token extracted from req.headers;
const JWKS = jose.createRemoteJWKSet(new URL("https://login.microsoftonline.com/" + microsoft.tenantId + "/v2.0/.well-known/openid-configuration"));
const { payload, protectedHeader } = await jose.jwtVerify(theToken, JWKS);  // <- JSON Web Key Set malformed

```
code:'ERR_JWKS_INVALID'
name:'JWKSInvalid'
message:'JSON Web Key Set malformed'

### Version

v 4.6.0

### Runtime

Node.js

### Runtime Details

VSC: 1.63.1 (system setup) Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f Date: 2021-12-14T02:13:54.292Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Code to reproduce

```js
const jose = require("jose");
const theToken = "eyJ...";   // Bearer Token extracted from req.headers;
const JWKS = jose.createRemoteJWKSet(new URL("https://login.microsoftonline.com/" + microsoft.tenantId + "/v2.0/.well-known/openid-configuration"));
const { payload, protectedHeader } = await jose.jwtVerify(theToken, JWKS);  // <- JSON Web Key Set malformed
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please provide steps to reproduce I can actually run.

**Comment by panva** [comment]
Ah. Nevermind. Exchange the well known endpoint with an actual jwks_uri value.
