### ISSUE TITLE
question: how to generate pair of keys?

### ISSUE THREAD

**Issue by Alexsey** [panva/jose#39]
The `JWK.generate` function can be used to generate private OR public key depends on the last parameter. Is there a way to generate a pair of private AND public keys?

I'm not strong in cryptography, but I can not even imagine how public key may be useful by its own and what is the difference between a single private key and symmetric key

**Comment by big-kahuna-burger** [comment]
You have that already.

If you do something like:
```js
const fs = require('fs')
const path = require('path')
const jose = require('@panva/jose')

const keystore = new jose.JWKS.KeyStore()
const jwkPrivateFilePath = path.resolve('private.json')
const jwkPublicFilePath = path.resolve('public.json')
keystore.generate('RSA', 2048, { use: 'sig' })
  .then(() => {
    fs.writeFileSync(
      jwkPrivateFilePath,
      JSON.stringify(keystore.toJWKS(true), null, 2)
    )
    fs.writeFileSync(
      jwkPublicFilePath,
      JSON.stringify(keystore.toJWKS(false), null, 2)
    )
  })
```
Turning point is `keystore.toJWKS(param)` where `param` is determining if other values will be exported.
Public part only consists of: "e", "n", "kty", "kid", "use"
See tests 3.3 and 3.4 of this library.
Have fun ;)

**Comment by panva** [comment]
> I'm not strong in cryptography, but I can not even imagine how public key may be useful by its own

I don't know either that's why generating private is the default.

> Is there a way to generate a pair of private AND public keys?

You just generate the private one, all private keys contain or are able to derive its public counterpart.

```js
const j = require('@panva/jose');

const jwk = j.JWK.generateSync('EC');

console.log(`JWK private`, jwk.toJWK(true))
console.log(`JWK public`, jwk.toJWK())

console.log(`PEM private`, jwk.toPEM(true))
console.log(`PEM public`, jwk.toPEM())
```

**Comment by big-kahuna-burger** [comment]
> I don't know either that's why generating private is the default.

This ☝️ !

**Comment by Alexsey** [comment]
@panva @big-kahuna-burger thank you for answering so fast! Now I can see how to use it :)
