### ISSUE TITLE
Throwing JWKSMultipleMatchingKeys error instead of returning only the last JWK

### ISSUE THREAD

**Issue by avidan-chen** [panva/jose#392]
### What happened?

When calling jwtVerify and passing a remote JWK Set, I'm getting an exception of JWKSMultipleMatchingKeys due to having two duplicate JWKs returned from the server.
I have no control over the server, so if possible I'm asking to modify the code to match the [RFC](https://datatracker.ietf.org/doc/html/rfc7517#section-4) :

"The member names within a JWK MUST be unique; JWK parsers MUST either
   reject JWKs with duplicate member names **or use a JSON parser that
   returns only the lexically last duplicate member name**, as specified
   in [Section 15.12](https://datatracker.ietf.org/doc/html/rfc7517#section-15.12) (The JSON Object) of [ECMAScript](https://datatracker.ietf.org/doc/html/rfc7517#ref-ECMAScript) 5.1 [ECMAScript]."

Thank you! Also this is a great project, thanks for your efforts!

### Version

v4.6.1

### Runtime

Node.js

### Runtime Details

Node v14.17.3

### Code to reproduce

```js
import { createRemoteJWKSet, jwtVerify } from 'jose-node-cjs-runtime';


const jwtVerifyResult = await jwtVerify(jwtFromHeaders, jwkSource, {
        issuer: (decodedJwtFromHeaders.payload as jwt.JwtPayload).iss,
        audience: (decodedJwtFromHeaders.payload as jwt.JwtPayload).aud
      });
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by avidan-chen** [comment]
This is where the error is thrown:

https://github.com/panva/jose/blob/main/src/jwks/local.ts#L139

**Comment by panva** [comment]
The behaviour implemented is intended and as per spec(s). The "lexical" section has nothing to do with your issue. 

It simply says that if two of the properties are present on an object to use the last one, which the json parser used already does. 

The solution to your issue is to ask the server operator to add unique key id ("kid") properties to the individual keys and then use the same kid header parameter in the jwt header.

**Comment by avidan-chen** [comment]
Got you, thanks. My bad - I was sure this RFC section referred to duplicate keys within a set, but I now realize it means duplicate keys within the same JWK.
The server already returns a unique id ("kid"), however when getting the JWK Set from the server, the kid appears twice.

Do you happen to have a reference which says the kid must be unique within the JWK Set? I need such proof to present it to the server owners.
Thanks!

**Comment by panva** [comment]
So it's not a unique "kid" is it...
