### ISSUE TITLE
jose.jwtVerify - Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by samuel-casasdray** [panva/jose#410]
### What happened?

On local (ng serve) it works perfectly with this code
`jose.jwtVerify(observer['token'], new TextEncoder().encode(environment.jwtKey)).then(...)`

But when I build the application to put it on the server, I got an error : 
`Cannot read properties of undefined (reading 'importKey')`

It seems to come from crypto because I search on the error (on main.js) and I found : 
`return jx.subtle.importKey("raw", n, {
                            hash: `SHA-${t.slice(-3)}`,
                            name: "HMAC"
                        }, !1, [e])`
when jx is `const jx = crypto;`

So I don't really know how to solve that...
I even do a `npm i crypto` just in case, but it doesn't solve the problem

### Version

4.6.1

### Runtime

Other (I will specify below)

### Runtime Details

It's angular 13.2.1

### Code to reproduce

```js
jose.jwtVerify(observer['token'], new TextEncoder().encode(environment.jwtKey)).then(...)
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This is more of Q&A question, please open a discussion in the Q&A category and, first and foremost, prepare a working example that can built and run if you wish to get assistance.

**Comment by samuel-casasdray** [comment]
UPDATE : I just update the version of the package from 3.6.1 to 3.8.1, and I got a new error (on the same code) :
`ReferenceError: CryptoKey is not defined`
(and same as before in local it works but not in prod)
