### ISSUE TITLE
Deno incorrect import?

### ISSUE THREAD

**Issue by joshhubers** [panva/jose#414]
### What happened?

Hello,

I'm running a `deno` project using `esm`. I don't have much experience with them, but upon adding a dependency to my imports I get the following error from my deno project:

```
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.141.0/node/zlib.ts' does not provide an export named 'inflateRaw'
    at <anonymous> (https://esm.sh/v85/jose@4.8.1/deno/jose.js:2:11728)
```

Probably from this import?
https://github.com/panva/jose/blob/3f1dd427b0d8d4ad25a14d2cb08003cf3825671e/src/runtime/node/zlib.ts#L2

Could also be an issue with the `deno_std`, but I'm not totally familiar with the environment yet.

https://deno.land/std@0.122.0/node/zlib.ts

### Version

4.8.1

### Runtime

Deno

### Runtime Details

deno 1.21.3 (release, x86_6-linux-gnu) v8 10.0.139.17 typescript 4.6.2

### Code to reproduce

```js
import {
  inflateRaw as inflateRawCb,
  deflateRaw as deflateRawCb,
} from "https://deno.land/std@0.122.0/node/zlib.ts";

console.log(inflateRawCb);
console.log(deflateRawCb);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
There is a deno-specific distribution, example import shown right at the top of the readme.
