### ISSUE TITLE
question: ignoreIat still tries to validate the content of the iat claim - could this be skipped?

### ISSUE THREAD

**Issue by ccpulse** [panva/jose#44]
The provider of the JWT I'm trying to verify has provided string values for several of the timestamp fields (iat, nfb etc) which currently cause the verify method to fail - even with the ignoreIat field set. Would it be possible to change this behaviour to only validate fields which are going to be used for the verification?

**Comment by panva** [comment]
@ccpulse it causes the method to fail on purpose. May I recommend to use the JWS interface and manually validate the returned payload until your provider produces a valid JWT?
