### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by richpryce** [panva/jose#467]
### What happened?

There is a small typo [here](https://github.com/panva/jose/blob/47d0d777a1ac90ff2ed0368fdab536db3d17aa8c/src/key/import.ts#L198)
I believe the message should read `TypeError: "pkcs8" must be PKCS8 formatted string`

### Version

4.8.1

### Runtime

Node.js

### Runtime Details

n/a

### Code to reproduce

```js
n/a
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Good find. Feel free to open a PR.

**Comment by richpryce** [comment]
Here you go!
https://github.com/panva/jose/pull/468
