### ISSUE TITLE
Private RSA key can not be created with n d e primitives only

### ISSUE THREAD

**Issue by majkrzak** [panva/jose#480]
### What happened?

On 3.x branch it is not possible to generate public RSA key without providing all derived parameters (p q dq dp di)
On 2.x branch there is flag for that: https://github.com/panva/jose/blob/v2.x/lib/jwk/import.js#L29

### Version

3

### Runtime

Node.js

### Runtime Details

-

### Code to reproduce

```js
-
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This will not be supported in the current versions of `jose`. You can certainly [plug the code that did this](https://github.com/panva/jose/blob/v2.x/lib/help/rsa_primes.js) into your own codebase if you absolutely need this resource intensive feature.
