### ISSUE TITLE
bug: TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by mediabuff** [panva/jose#49]
Get error on 

import {Issuer} from 'openid-client';

***********
TypeError: The "original" argument must be of type Function
promisify

GoogleApi.Tester/GoogleApi.Tester/ClientApp/node_modules/util/util.js:605
  602 | var kCustomPromisifiedSymbol = typeof Symbol !== 'undefined' ? Symbol('util.promisify.custom') : undefined;
  603 | 
  604 | exports.promisify = function promisify(original) {
> 605 |   if (typeof original !== 'function') throw new TypeError('The "original" argument must be of type Function');
  606 | 
  607 |   if (kCustomPromisifiedSymbol && original[kCustomPromisifiedSymbol]) {
  608 |     var fn = original[kCustomPromisifiedSymbol];
View compiled
(anonymous function)

GoogleApi.Tester/GoogleApi.Tester/ClientApp/node_modules/jose/lib/jwk/key/rsa.js:44
  41 | 
  42 | var Key = require('./base');
  43 | 
> 44 | var generateKeyPair = promisify(async);
  45 | var SIG_ALGS = ['PS256', 'RS256', 'PS384', 'RS384', 'PS512', 'RS512'];
  46 | var WRAP_ALGS = ['RSA-OAEP', 'RSA1_5'];
  47 | 
View compiled

**Comment by panva** [comment]
Please follow the bug report template.

**Comment by panva** [comment]
Hi @mediabuff,

You’re clearly transpiling the library and its dependencies through webpack or similar. 

The supported runtime is Node.js and your transpiling pipeline is requiring its own polyfill of the node crypto module. That clearly ain’t gonna work because a webpackable crypto doesn’t have all the necessary APIs

**Comment by athornton2012** [comment]
@panva Do you know of a work around for this?

**Comment by panva** [comment]
Don’t transpile code for node runtime?

**Comment by panva** [comment]
> 👎 

I don't know what else to tell you. The library works as intended when used as intended. If people transpile code INCLUDING dependencies then there are no guarantees the transpiled node standard lib modules are the same.

**Comment by athornton2012** [comment]
Totally understand. Just think you could be kinder in your responses :) Thanks for your help, though!

**Comment by pkozul** [comment]
Really weird. I had the same issue running the code 'as is'. When I updated node.js to v10.16.3, the problem went away.

**Comment by panva** [comment]
> Really weird. I had the same issue running the code 'as is'. When I updated node.js to v10.16.3, the problem went away.

Well, the supported node runtime is `^10.13.0 || >=12.0.0` so again - your runtime didn't have the required [`crypto.generateKeyPair`](https://nodejs.org/docs/latest-v10.x/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback) function.

**Comment by big-kahuna-burger** [comment]
> Totally understand. Just think you could be kinder in your responses :) Thanks for your help, though!

@panva is polite when you ask the right questions.
More important - he is precise when answering issues/questions. 
Watching this package on github showed me that this feature showed up like 10 times now at least. if you go trough issues, you will find them.
I think he is just a bit when people don't try to find solution to their problem in older
I think politeness is something much less important than getting a proper and to the point response in <24h.

**Comment by panva** [comment]
`¯\_(ツ)_/¯` in this particular instance i just felt like the question was already answered by the previous conversation, let alone by other issues. I'm like a teddy bear otherwise.

**Comment by big-kahuna-burger** [comment]
Yeah, _disappointed_ is the word I was looking for :)

**Comment by impactcolor** [comment]
@panva Trying to figure this out.  ```
function youreAStinkingJerk() {
let teddyBear = false;
console.log(teddyBear)
}
```

**Comment by panva** [comment]
Let me be very clear here. Transpiling the code is not the biggest offender here, it's that during this process the tools you use, such as `webpack`, replace the native [`crypto`](https://nodejs.org/api/crypto.html) module require with a shim / polyfill such as https://github.com/crypto-browserify/crypto-browserify which lacks the necessary APIs, such as `generateKeyPair`.

This is very clearly a Node.js runtime module (for now at least). It makes use of native node's `crypto`. If you try to use this in a browser, it won't work, if you try to use this in react native, it won't work, if you use this in electron or Node.js (the only declared supported runtimes) you mustn't transpile and shim native modules.

It's disheartening to have to face frustrated developers over something they caused themselves by not owning your code pipeline properly.

**Comment by panva** [comment]
A quick note, i've release a new major (v3.x) which is now a universal module with 0 dependencies and now works the same in the browser as well as node
