### ISSUE TITLE
question: using crit option to require payload

### ISSUE THREAD

**Issue by vrseraphin** [panva/jose#51]
**Describe the bug**

JWT.verify fails with errors indicating critical claims are missing even when the claim names are passed within the crit attribute of the options object.  These claims are indeed there in the "payload".  The library at present seems to be looking for these only within the header portion.

The specific issue is within jwsVerify and the call into the validateCrit
[josetest2.zip](https://github.com/panva/jose/files/3737152/josetest2.zip)

**To Reproduce**

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**
I expect the JWT to be successfully validated with the identified critical claims are within the payload rather than the header.

**Environment:**
 - `jose` version: [e.g. v1.0.0]
 - node version: [e.g. v12.0.0]

**Additional context**

 - [x ] the bug is happening on latest `jose` too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
@vrseraphin the `crit` option is for specifications extending how a payload is being processed. Such an extension is the `b64` from [rfc7797](https://tools.ietf.org/html/rfc7797)

Also the docs are clear on this

> `crit`: `string[]` Array of Critical Header Parameter names to recognize.

Its use is limited to acknowledging an extension may be used in a given context, it is not intended for requiring certain claims to be present.
