### ISSUE TITLE
importPKCS8() returns ERR_OSSL_ASN1_HEADER_TOO_LONG

### ISSUE THREAD

**Issue by alexbelyeu** [panva/jose#512]
### What happened?

I'm stumped. I am trying to sign a token as soon as my API is called. The code is so simple that I feel like maybe I'm not using this correctly.

I have a Next.js (13.2.1) app with a `pages/api/appstorereviews.ts` (an [API route](https://nextjs.org/docs/api-routes/introduction)). The idea is that by calling this endpoint `https://${baseUrl}/api/appstorereviews`, it will sign a token and eventually use this same token to make a request elsewhere.

However, when I pull the private key from my env variables and use it with :

```const pKey = await jose.importPKCS8(process.env.APPSTORE_PRIVATE_KEY, "ES256")```

I get the following error:
```
{
    "error": {
        "library": "asn1 encoding routines",
        "reason": "header too long",
        "code": "ERR_OSSL_ASN1_HEADER_TOO_LONG"
    }
}
```

What am I doing wrong?

### Version

4.13.1

### Runtime

Node.js

### Runtime Details

Next.js 13.2.1, Node 18.x

### Code to reproduce

```js
/// api/appstorereviews.ts

export default async function handler(req, res) {
 try {
  const pKey = await jose.importPKCS8(process.env.APPSTORE_PRIVATE_KEY, "ES256")
  ...
  res.status(200).json(...) 
 } catch (error) {
  res.status(500).json({error}) 
 }
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by alexbelyeu** [comment]
I forgot to mention one thing: This does not happen when running the code locally (`http://localhost:3000/api/appstorereviews`). However, when I push this same code to production and call that API, that's when the error happens.

**Comment by panva** [comment]
> However, when I push this same code to **_production_**

Well, check your environment variables' values and format.
