### ISSUE TITLE
Invalid ES256 signatures generated with Node 12.15 but not 12.16.0

### ISSUE THREAD

**Issue by adriancable** [panva/jose#520]
### What happened?

This is the same issue reported by @yuanpli in #346, which unfortunately was prematurely closed without resolution.

The actual problem: Jose does not generate correct ES256 signatures for JWTs when run under Node 12.15. Everything is fine in Node 12.16.0.

The signatures in 12.15 are immediately obviously broken by visual inspection, as (when base64 decoded) they are 70 characters long (when they should be 64). Running under Node 12.16.0 generates valid signatures.

Here's a pair of JWTs (just the signature part, rest is fine) generated by the same code, one under 12.15 and one under 12.16.0:

Fails (Node 12.15): XXX.XXX.MEQCIH6_WVoPKUxdM3k0dvLrA7711MYZznF7OqPGeOaSZ8YnAiAGMryiPWo18qykMXG4EOy5HbmnsfC6k1TWlDslwTKhHQ

Succeeds (Node 12.16.0): XXX.XXX.SORfQtuRXGeTpC_cdJ__eEdq_Wa42kfyjszCAcR43IfXeL9cibypj2ZNNrDN4-dk5vMewDPGO5vQUkrMOJZ2Gw

Note that jsonwebtoken generates correct signatures even with Node 12.15.0.

So it appears that jose doesn't support Node 12.15.0, at least for ES256. This should be called out (or worked around).

### Version

4.11.2

### Runtime

Node.js

### Runtime Details

12.15 (fails), 12.16.0 (works)

### Code to reproduce

```js
Just generate a JWT with an ES256 signature. Any payload, any header, doesn't matter. Observe the incorrect length of the signature component (70 bytes vs 64 bytes).
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by adriancable** [comment]
Edit to add: cause found. `node_key.js` has the following:

`return { dsaEncoding: 'ieee-p1363', key };`

Unfortunately `dsaEncoding` is only allowable as an option starting in node 12.16.0.

So I think it should be made clear that jose does not support Node earlier than 12.16.0 for ES256 (and maybe others).

**Comment by panva** [comment]
Node.js 12 has reached End-Of-Life a year ago, the minimum version supported (^12.19.0, not 12.16.0, has been mentioned at the top of the [tracker](https://github.com/panva/jose/issues/262) for a half a year afterwards). The minimum v12 version is now 2.5 years old, same as `jose@4`, the LTS releases for v14 and v16 were available at that time already. In short, it's not worth working around and has never been a concern before.

I added a minimum v12.x version footnote to the [Node.js Support](https://github.com/panva/jose/issues/262) page.

**Comment by panva** [comment]
I went back and forth on engines entry on a universal library. It is what it is atm after much deliberation.

Bottom line right now is that any maintained LTS or current node release is supported. Node 12 is EOL and so is also my will to add minimum engines entry because of it.
