### ISSUE TITLE
Encrypt function of FlattenedEncrypt doesn't work with the Uint8array key type.

### ISSUE THREAD

**Issue by parviz-mv** [panva/jose#522]
### What happened?

Encrypt function of FlattenedEncrypt accepts two key types (KeyLike and Uint8array) but doesn't work with the Uint8array key type. Working only with KeyLike type of public key.

![Screenshot 2023-04-11 at 11 29 15](https://user-images.githubusercontent.com/109977975/231074969-426abc7e-ebe0-40f2-8205-0d697e725b2d.png)

### Version

4.13.1

### Runtime

Node.js

### Runtime Details

node version - 16.14.2 and OS is arm64 

### Code to reproduce

```js
const keyPair = await jose.generateKeyPair("ECDH-ES+A256KW", {
    crv: "X25519",
  });

const flattenedEncrypt = new jose.FlattenedEncrypt(
    new Uint8Array(Buffer.from("Hello world"))
  );
const publicKeyUint8Array = new Uint8Array(
 Buffer.from(JSON.stringify(keyPair.publicKey)) // I also tried convert keyPair in Uint8Array and use in encrypt function
      );
  const flattenedJwe = await flattenedEncrypt
    .setProtectedHeader({ alg: "ECDH-ES+A256KW", enc: "A256GCM" })         
    .encrypt(keyPair.publicKey); //here I tried to use 'publicKeyUint8Array'
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
> Encrypt function of FlattenedEncrypt accepts two key types (KeyLike and Uint8array) but doesn't work with the Uint8array key type. Working only with KeyLike type of public key.

Hello. That's both the intended and documented behaviour.

**Comment by parviz-mv** [comment]
@panva  Can you point me path , where is documented behaviour? In documents I can't  found it. Thanks!
