### ISSUE TITLE
Error building typescript in 'ts-jose' missing declaration files Version 4.14.0 

### ISSUE THREAD

**Issue by mira-ayman95** [panva/jose#526]
### What happened?

When attempting to build my project, an error occurred due to missing declaration files for the 'ts-jose' module. The error message suggests installing '@types/ts-jose' or adding a new declaration file. The issue seems to have been caused by the release of ts-jose 4.14.0 on 2023-04-17.

Steps to reproduce:

npm install ts-jose@4.14.0
npm start
Observe the error message regarding missing declaration files for 'ts-jose'

Expected behavior:
should build successfully without any errors.

Actual behavior:
The build failed due to missing declaration files for 'ts-jose'.

Environment:

Node version: v14.20.0
Typescript version: 4.6.3
Possible solution:
Update the code to include the declaration files for 'ts-jose' or install '@types/ts-jose' as suggested in the error message.

Additional context:
The issue seems to have been caused by the release of ts-jose 4.14.0 on 2023-04-17.

### Version

ts-jose@4.14.0

### Runtime

Node.js

### Runtime Details

Node version: v14.20.0 Typescript version: 4.6.3

### Code to reproduce

```js
npm install ts-jose@4.14.0
npm start
Observe the error message regarding missing declaration files for 'ts-jose'
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This is not the issue tracker for ts-jose.
