### ISSUE TITLE
bug: cannot retrieve key from JWKS when specifiying alg and use='enc'

### ISSUE THREAD

**Issue by henkvhest** [panva/jose#53]
**Describe the bug**

The following leads to an undefined return value, but I would expect the key to be returned
```
const { JWKS } = require('@panva/jose');
const keystore = new JWKS.KeyStore();

async function test(){
	await keystore.generate('RSA', 2048, {
			use: 'enc',
			alg: 'RSA-OAEP-256',
			kid: 'gHKpbutlpxI6PrJKHwWWUYnP1XY5uZv4hoNadnwki8X',
		});
// returns undefined but would expect the key to be logged
console.log(keystore.get({alg: 'RSA-OAEP-256', use: 'enc'});
}

test();
```

**Expected behaviour**
I would expect a key to be returned in this case instead of undefined.

**Environment:**
 - `jose` version: v1.10.1 (and also on 1.9.2 of @panva/jose)
 - node version: v10.16.3

 - [X] the bug is happening on latest `jose` too.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
RSA-OAEP-256 JWE algorithm is only supported when Node.js >= 12.9.0 runtime is detected, as per the `Detailed feature matrix (Click to expand)` notes. Earlier runtimes do not have the option to specify `oaepHash` - see [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2019-08-20-version-1290-current-targos).
