### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by dargmuesli** [panva/jose#534]
### What happened?

Updated from v4.14.1 to v4.14.2: https://github.com/maevsi/maevsi/pull/1215
Now there seems to be a loop in the typescript types:
![image](https://user-images.githubusercontent.com/4778485/234795596-52bd0bae-491e-4023-9a65-babe499dd41b.png)

### Version

4.14.2

### Runtime

Node.js

### Runtime Details

typescript 5.0.4

### Code to reproduce

https://github.com/maevsi/maevsi/actions/runs/4817158729/jobs/8577533577?pr=1215#step:7:1785

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please provide a minimal reproduction example, a simple TS project that exhibits this issue with clear npm-based install and build steps.

You should narrow the types of the payload properties you access or at the very least type assert them.

**Comment by dargmuesli** [comment]
Sure, am just currently busy and wanted to get that possible regression reported as quick as possible :) will setup a minimal repro in the coming days if still necessary by then 🤞

**Comment by panva** [comment]
Feel free to come back with a repro on your own time.

**Comment by panva** [comment]
Didn't mean to sound harsh, and even re-reading it still doesn't sound like so to me. What I meant is, feel free to come back with a repro anytime not being pressured by an open issue that's waiting on you, that's all :)

**Comment by dargmuesli** [comment]
The issue is in the following section:

https://github.com/panva/jose/blob/f079ca3cd678cbfb6cfb0a95bdd404eb20faf4af/src/types.d.ts#L94-L97

There is a loop between JsonValue and JsonObject.

**Comment by dargmuesli** [comment]
Based on https://stackoverflow.com/a/50516408/4682621 it might be a solution to define `JsonObject` like this:

```ts
type JsonObject<T> = {
  [K in keyof T]?: T[K] extends object ? JsonObject<T[K]> :
    T[K] extends JsonPrimitive | JsonArray ? T[K] : never
}
```

But I'm not that kind of typescript pro, so please validate that suggestion thoroughly!

**Comment by panva** [comment]
Curcular referencing is not an issue and I've had this code in other projects for a long time with no issues. That's why I need a minimal reproduction, to be able to rule out that this isn't a problem caused by something else in your stack. From the looks of it in your screenshot it is.
