### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Vilx2** [panva/jose#54]
**Description**
JWT token verification with RS256 fails even though all the keys are in order. The exception is `JWSVerificationFailed: signature verification failed`.

I tracked down the problem to the files `key_object.js` and `rsassa.js`. The first one contains a polyfill for the `KeyObject` class, however the polyfill also defines an extra method `asInput()`. Then the second file uses this method. However starting with Node version 11.13.0 the native `KeyObject` is exported and the polyfill isn't used anymore. This causes the call to `asInput()` to fail in `rsassa.js` since the method doesn't exist on the native object.

**Environment:**
 - `jose` version: 1.9.2
 - node version: 11.13.0 and above (I triggered this on 11.16)

**Comment by panva** [comment]
https://github.com/panva/jose/blob/master/package.json#L72-L74

The supported runtime is ^10.13.0 || >=12.0.0

v11.x is not something i will be figuring out backports for since it has reached its end of life in June.

**Comment by Vilx2** [comment]
Oh, ok. I didn't notice that. My apologies!

**Comment by panva** [comment]
np
