### ISSUE TITLE
Unable to build Angular project with Jose

### ISSUE THREAD

**Issue by JoinThisBand** [panva/jose#549]
### What happened?

Angular was [impacted by an issue with Babel today](https://github.com/angular/angular-cli/issues/25496#issuecomment-1623604147), which was resolved by a rollback by the Babel team.

Though I know jose is not dependant on Babel, I'm seeing new errors when trying to build my project, which seem to be related:

    ./node_modules/jose/dist/browser/lib/decrypt_key_management.js:14:22 - Error: Module parse failed: Unexpected token (14:22)
    File was processed with these loaders:
     * ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js
     * ./node_modules/source-map-loader/dist/cjs.js
    You may need an additional loader to handle the result of these loaders.
    | import isObject from './is_object.js';
    | import { unwrap as aesGcmKw } from './aesgcmkw.js';
    > /*#__PURE__*/function () {
    |   _temp = function () {
    |     function decryptKeyManagement(_x, _x2, _x3, _x4, _x5) {

There are similar error messages for:

- ./node_modules/jose/dist/browser/lib/encrypt_key_management.js
- ./node_modules/jose/dist/browser/runtime/decrypt.js
- ./node_modules/jose/dist/browser/runtime/encrypt.js

Any guidance to resolve this issue would be helpful.

### Version

4.14.4

### Runtime

Node.js

### Runtime Details

v18.12.1 on Mac

### Code to reproduce

```js
Add Jose to an Angular project and run `ng serve`.
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
There is very little I can do about other project's bundling mechanisms.
