### ISSUE TITLE
Cannot verify id token using remote jwks

### ISSUE THREAD

**Issue by hanssonduck** [panva/jose#561]
### What happened?

I'm trying to verify an id token from Google using wrangler but it's not working. This error is thrown: `TypeError: Key for the RS256 algorithm must be of type CryptoKey. Received an instance of Uint8Array`

### Version

4.14.4

### Runtime

Cloudflare Workers

### Runtime Details

Workers running with `wrangler dev`

### Code to reproduce

```js
const googleKeys = createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'),)
const result = await jwtVerify(/* id token */, googleKeys)
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by hanssonduck** [comment]
I'm closing this. There was an unrelated issue in my code.

**Comment by justinmchase** [comment]
I'm having the same issue, what was the issue in your code?

**Comment by hanssonduck** [comment]
> I'm having the same issue, what was the issue in your code?

The issue was with `SignJWQ`. Ensure you use the right algorithm for your key. I mistakenly used `RS256` instead of `HS256`, causing the error.
