### ISSUE TITLE
Can't verify azure token

### ISSUE THREAD

**Issue by justinmchase** [panva/jose#564]
### What happened?

Using a valid azure token, I can't seem to figure out how to verify it using this library.

```json
 {
        "name": "JWSSignatureVerificationFailed",
        "message": "signature verification failed",
        "code": "ERR_JWS_SIGNATURE_VERIFICATION_FAILED",
        "stack": "JWSSignatureVerificationFailed: signature verification failed\n    at flattenedVerify (https://deno.land/x/jose@v4.14.4/jws/flattened/verify.ts:159:11)\n    at eventLoopTick (ext:core/01_core.js:183:11)\n    at async compactVerify (https://deno.land/x/jose@v4.14.4/jws/compact/verify.ts:65:20)\n    at async jwtVerify (https://deno.land/x/jose@v4.14.4/jwt/verify.ts:58:20)\n    at async AuthService.verify (file:///home/justin/code/deploy-approval/src/services/auth/mod.ts:8:42)\n    at async AuthController.handler (file:///home/justin/code/deploy-approval/src/controllers/auth/mod.ts:25:21)\n    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:80:7)\n    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:80:7)\n    at async allowedMethods (https://deno.land/x/oak@v12.6.0/router.ts:741:7)\n    at async dispatch (https://deno.land/x/oak@v12.6.0/middleware.ts:80:7)"
}
```

### Version

4.14.4

### Runtime

Deno

### Runtime Details

deno oak

### Code to reproduce

```js
const azureTenantId = "22dddbf3-6a10-486d-94dc-b3eca6a4d13e";
const JWKS = createRemoteJWKSet(new URL(`https://login.microsoftonline.com/${azureTenantId}/discovery/keys`));
export class AuthService {
  public async verify(jwt: string) {
    const { payload } = await jwtVerify(jwt, JWKS);
    return payload;
  }
}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by justinmchase** [comment]
Here is the open id configuration url:
https://login.microsoftonline.com/22dddbf3-6a10-486d-94dc-b3eca6a4d13e/.well-known/openid-configuration

**Comment by panva** [comment]
Hello @justinmchase 

> Using a valid azure token, I can't seem to figure out how to verify it using this library.

That's not something a bug tracker is for. There is no bug presented in your issue. Please open a q&a discussion instead for non-bugs. 

If you are certain there is a bug in the library then please prepare actual steps to reproduce, that means code that can be copy pasted and run that ends with the issue reproduced.

**Comment by justinmchase** [comment]
I managed to resolve it and will add some notes here in case anyone else experiences the issue, but apparently Microsoft produces _unverifiable_ tokens unless you add a special scope when requesting the access token. Its quite confusing but here are some docs for any future readers:

#### description of the issue
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609#issuecomment-524434987

#### how to add a scope
https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis

#### oath client code with an example scope
```ts
export const oauth = new OAuth2Client({
  clientId: config.azureClientId,
  clientSecret: config.azureClientSecret,
  redirectUri: config.azureRedirectUri,
  authorizationEndpointUri:
    "https://login.microsoftonline.com/22dddbf3-6a10-486d-94dc-b3eca6a4d13e/oauth2/v2.0/authorize",
  tokenUri:
    "https://login.microsoftonline.com/22dddbf3-6a10-486d-94dc-b3eca6a4d13e/oauth2/v2.0/token",
  defaults: {
    scope: "api://ce608137-10fc-4b3e-824b-a3b601a2f424/Example openid",
  },
});
```
