### ISSUE TITLE
bug: detached jws encoding error

### ISSUE THREAD

**Issue by OR13** [panva/jose#57]
**Describe the bug**
The way utf-8 encoding is applied to detached jws causes incompatibility issues.

**To Reproduce**

https://github.com/transmute-industries/json-ld-sig-detached-jws/issues/1

Steps to reproduce the behaviour:

1.  Try to sign with b64: false some arbitrary binary
2. observe the jws that is produced does not match expectations for b64 false
3. base64url decode assumes utf8 encoded characters

**Expected behaviour**
base64url decode applied to the payload should not assume utf8.

**Environment:**
 "@panva/jose": "^1.9.3",
"jose": "^1.16.0",
 - node version: v12.0.0

**Additional context**

 - [X ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by OR13** [comment]
Also, @panva Thank you for this library! I used it to test interoperability with browser JWS implementations using secp256k1 / ed25519. I have some JSON-LD signature suites that I need to update to support the features of jsonld-signatures, which is the main reason I came across this issue, and these JWS use `b64: false` detached jws.

**Comment by panva** [comment]
https://github.com/panva/jose/blob/master/docs/README.md#jwsverifyjws-keyorstore-options

i think you should be providing parse:false to just get a buffer back if you’re working with b64:false and arbitrary buffers

**Comment by panva** [comment]
But please provide a code snippet so that i don’t have to guess what you’re doing.

**Comment by OR13** [comment]
Sorry, I should have provided a more minimal example, I will do so.

**Comment by OR13** [comment]
https://gist.github.com/OR13/862380ac861ee2d937df2653c22ea44a

```
git clone git@gist.github.com:/862380ac861ee2d937df2653c22ea44a.git;
cd 862380ac861ee2d937df2653c22ea44a;
npm i
npm run test
```

**Comment by panva** [comment]
Thank you, i can work with this.

**Comment by panva** [comment]
@OR13 

i have the sign fixed to produce correct signature but riddle me this, how will you ever verify the detached signature when you can't reconstruct a valid looking JWE serialization with binary buffer being the payload?

**Comment by panva** [comment]
can you take a look at f30584b?

**Comment by panva** [comment]
can you take a look at daabedc?

**Comment by OR13** [comment]
Thanks, I retested, and your fix appears to have resolved this issue.
