### ISSUE TITLE
Bun support ED25519

### ISSUE THREAD

**Issue by zamplyy** [panva/jose#574]
### What happened?

Hi, thanks for a great library.
I was trying to migrate my express app to Bun instead of Node.
When doing so i stumbled upen this issue.

```
JOSENotSupported: Invalid or unsupported "alg" (Algorithm) value
 code: "ERR_JOSE_NOT_SUPPORTED"
```

Even though it seems to be supported [Here](https://github.com/panva/jose/issues/471)

### Version

v.4.14.0

### Runtime

Other (I will specify below)

### Runtime Details

Bun v1.0

### Code to reproduce

```js
import {importPKCS8} from 'jose';

const key = await importPKCS8(**CERT**, 'ED25519');
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
The algorithm name is `EdDSA`, not `Ed25519` ([yet](https://www.ietf.org/archive/id/draft-jones-jose-fully-specified-algorithms-01.html))
