### ISSUE TITLE
Bun: SyntaxError: Import named 'KeyObject' not found in module 'crypto'.

### ISSUE THREAD

**Issue by Paultje52** [panva/jose#581]
### What happened?

I'm migrating from nodejs to bun in my sveltekit project (using vite to build).
In the readme of `jose`, it states that bun is a supported runtime. I'm having problems with `jsonwebtoken`, so I'm trying to migrate to `jose`.

I expect for `jose` to work, but it doesn't when I specify bun to use bun's runtime (using `bun --bun run vite dev`).

#### Error
```ts
9:18:19 AM [vite] Error when evaluating SSR module /src/lib/server/util/jsonwebtoken.ts: failed to import "jose"
|- SyntaxError: Import named 'KeyObject' not found in module 'crypto'.
    at processTicksAndRejections (:55:39)

9:18:19 AM [vite] Error when evaluating SSR module /src/lib/server/functions/resolveSession.ts: failed to import "/src/lib/server/util/jsonwebtoken.ts"
|- SyntaxError: Import named 'KeyObject' not found in module 'crypto'.
    at processTicksAndRejections (:55:39)

9:18:19 AM [vite] Error when evaluating SSR module /src/hooks.server.ts: failed to import "/src/lib/server/functions/resolveSession.ts"
|- SyntaxError: Import named 'KeyObject' not found in module 'crypto'.
    at processTicksAndRejections (:55:39)

{"originalLine":55,"originalColumn":39}
{"originalLine":55,"originalColumn":39}
```

### Version

4.14.6

### Runtime

Other (I will specify below)

### Runtime Details

Bun v1.0.3

### Code to reproduce

```js
import { createSecretKey } from "crypto";
import * as jose from "jose";

const key = createSecretKey(process.env.JWT_SECRET, "utf8");

export function jwtSign(payload: string): Promise<string> {
  return new jose.SignJWT({ id: payload })
    .setProtectedHeader({ alg: "HS256" })
    .sign(key);
}

export async function jwtVerify(token: string): Promise<string> {
  const { payload } = await jose.jwtVerify(token, key);
  return payload.id.toString();
}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Bun is a supported runtime when running in its regular runtime settings. Bun's `node:crypto` is not complete. See https://bun.sh/docs/runtime/nodejs-apis#node-crypto

When Bun completes its node compatibility layer it'll work even under your settings. Maybe stick to Node.js for now if you plan on relying on Node.js APIs.

**Comment by Paultje52** [comment]
The [`--bun`](https://bun.sh/docs/cli/run#bun) flag indicates that the runtime used (for example by vite) should be bun, not nodejs. And using the bun runtime I'm having this issue. So that means that the bun runtime isn't fully supported by jose.

Can it be possible to add a warning or something to the readme that the bun runtime isn't fully supported?

**Comment by panva** [comment]
Look at your steps to reproduce, please.

```
import { createSecretKey } from "crypto";
```

This is a Node.js API that is not available in Bun. That's where your steps to reproduce fail.

```
import * as jose from "jose";

const secret = new TextEncoder().encode("my-very-not-secure-secret");

const jwt = await new jose.SignJWT({ id: 1 })
    .setProtectedHeader({ alg: "HS256" })
    .sign(secret);

const verified = await jose.jwtVerify(jwt, secret)

console.log('🎉🎉🎉\n', verified)
```

```
bun --bun some.ts
🎉🎉🎉
 {
  payload: {
    id: 1
  },
  protectedHeader: {
    alg: "HS256"
  }
}
```
