### ISSUE TITLE
Mocking URLs with msw/nock doesn't work with named imports.

### ISSUE THREAD

**Issue by dhruvinmakwana19** [panva/jose#584]
### What happened?

I am writing integration tests to mock the auth mechanism in my application. To do this I am using [mock-jwks](https://github.com/levino/mock-jwks/tree/main) which internally uses the [MSW ](https://mswjs.io/) library to mock the responses of creating `jwks` in `createRemoteJWKSet`. The problem I am facing right now is since he module fetches the remote `JWKs` through the named import of `http`/`https` modules, MSW is not able to monkey patch the `http`/`https` modules. I have found possible issues relating to this problem and there seems to be a possible solution implemented [here](https://github.com/stripe/stripe-node/pull/1866).

Related issues:
https://github.com/stripe/stripe-node/issues/1844
https://github.com/nock/nock/issues/2461

### Version

4.11.0

### Runtime

Browser

### Runtime Details

Node - v16.20.2 with ESM

### Code to reproduce

```js
//test setup
test('Test with mocked jkwsUri', async () => {
  const jwksMock = createJWKSMock(
    'https://keycloak.somedomain.com',
    '/auth/realm/application/protocol/openid-connect/certs'
  )
  // We start our app.
  const server = createApp().listen()
  const request = supertest(server)
  jwksMock.start()
  const access_token = jwksMock.token({
    aud: 'private',
    iss: 'master',
  })
  const { status } = await request
    .get('/')
    .set('Authorization', `Bearer ${access_token}`)
  expect(status).toEqual(200)
})
// app


function auth() {
  const getKey = createRemoteJWKSet(new URL("https://keycloak.somedomain.com/auth/realm/application/protocol/openid-connect/certs"));

  return async function middleware(ctx, next) {

    const [type, accessToken] = ctx.request.get('Authorization').split(' ');

    try {
      const { payload } = await jwtVerify(accessToken, getKey, { issuer, audience });
    } catch (err) {
      ctx.throw(401);
    }
    return next();
  };
}

const createApp = () => {
  const app = new Koa()
  app.use(auth())
  const router = new Router()
  // This route is protected by the authentication middleware
  router.get('/', (ctx) => {
    ctx.body = 'Authenticated!'
  })
  app.use(router.middleware())
  return app
}
export default createApp
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
The library does not use named imports from http/https [^1] and its own tests successfuly mock the jwks response using nock [^2].

[^1]: https://github.com/panva/jose/blob/5e5970573eee039725631eddb50e36baf7b3f552/src/runtime/node/fetch_jwks.ts#L1-L2
[^2]: https://github.com/panva/jose/blob/5e5970573eee039725631eddb50e36baf7b3f552/test/jwks/remote.test.mjs
