### ISSUE TITLE
[ES384] adding a single letter to the signature part causing a successful verification

### ISSUE THREAD

**Issue by mohamedsRH** [panva/jose#589]
### What happened?

When adding a single letter to the signature part jose.compactVerify doesn't throw exception

this is the valid jws
"eyJhbGciOiJFUzM4NCJ9.eyJyZWdpc3RyYXRpb24iOnsidGVzdCI6InRlc3QifX0.FT0speiSJ8bkS69SOd-mRBlyWrEILLi4EG6NjUFqAeN16uqRSJlExNE0TCYPv-wDbX7rBO0aWyr1Cu6dk86aFkSKhRiXnFkMOQ5ySg4eBa4DMS2bTQczmYw4guA7l4_2",

and this is the jwk with additional letter in the end of signature part
"eyJhbGciOiJFUzM4NCJ9.eyJyZWdpc3RyYXRpb24iOnsidGVzdCI6InRlc3QifX0.FT0speiSJ8bkS69SOd-mRBlyWrEILLi4EG6NjUFqAeN16uqRSJlExNE0TCYPv-wDbX7rBO0aWyr1Cu6dk86aFkSKhRiXnFkMOQ5ySg4eBa4DMS2bTQczmYw4guA7l4_2a"

"jwk": {
    "kty": "EC",
    "x": "zuwYMngeqd5f8oYbfPNndHLtN4gRr-aKfhxsWU9QkHtMFGRD5YQhDGsyoL4dmkCb",
    "y": "6-TU0vmPXZXJtcOA9wD4KrbmHZ8RLSI6aGbGTBHDAa6bHlIzJBz9bj2LFpyk6M9K",
    "crv": "P-384"
}

### Version

4.13.2

### Runtime

Other (I will specify below)

### Runtime Details

node version 18, OS windows 11 and Ubuntu 12

### Code to reproduce

```js
async signatureVerification() {
    try {
          const jwk = "eyJhbGciOiJFUzM4NCJ9.eyJyZWdpc3RyYXRpb24iOnsidGVzdCI6InRlc3QifX0.FT0speiSJ8bkS69SOd-mRBlyWrEILLi4EG6NjUFqAeN16uqRSJlExNE0TCYPv-wDbX7rBO0aWyr1Cu6dk86aFkSKhRiXnFkMOQ5ySg4eBa4DMS2bTQczmYw4guA7l4_2a"

const jwk = {
    "kty": "EC",
    "x": "zuwYMngeqd5f8oYbfPNndHLtN4gRr-aKfhxsWU9QkHtMFGRD5YQhDGsyoL4dmkCb",
    "y": "6-TU0vmPXZXJtcOA9wD4KrbmHZ8RLSI6aGbGTBHDAa6bHlIzJBz9bj2LFpyk6M9K",
    "crv": "P-384"
}
  publicKey = await jose.importJWK(jwk);
      await jose.compactVerify(jws, publicKey);
      return true;
    } catch (error) {      
      return false;
    }
  }
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This is just how base64url encoding works, you changing or adding a character at the end does not necessarily change the encoded binary value in all cases.

**Comment by panva** [comment]
Run the signature before/after through base64url decode and you'll see for yourself.

**Comment by panva** [comment]
Again, run the value by base64url decode and see the binary encoded value not change when you make your addition.  You're not describing a bug nor a security vulnerability, just how base64url works sometimes

**Comment by mohamedsRH** [comment]
Okey i have to convince our QA team because using https://jwt.io/ it returns  **Invalid Signature**
 when adding a character to the end of the signature part :p
