### ISSUE TITLE
Check for `jwk.oth` should also check for `null` value

### ISSUE THREAD

**Issue by swain** [panva/jose#594]
### What happened?

Currently, `importJWK(...)` throws a `JWKUnsupported` error if the JWK includes any value for `oth` other than `undefined`, including `null`.

So, calling `importJWK(...)` with a key that contains e.g. `oth: null` results in this error:
```
JOSENotSupported: RSA JWK "oth" (Other Primes Info) Parameter value is not supported
```

This is the line of code that results in the error: https://github.com/panva/jose/blob/cc9eee9acf7e889b7dd28c5587484e647e22fee7/src/key/import.ts#L184C1-L188C8

This strikes me as difficult + problematic behavior. Various serialization tools might serialize empty values as `null` rather than "empty" (i.e. `undefined`).

Can this logic be updated to also account for `null` values? e.g.

```typescript
if (jwk.oth !== undefined && jwk.oth !== null) { // <-- also account for `null`
  throw new JOSENotSupported(
    'RSA JWK "oth" (Other Primes Info) Parameter value is not supported',
  )
}
```

### Version

v4.x

### Runtime

Node.js

### Runtime Details

Node 16 or 18

### Code to reproduce

```js
import { importJWK } from 'jose';

const jwk = {
  kty: 'RSA',
  e: 'AQAB',
  use: 'sig',
  kid: '12345',
  alg: 'RS256',
  n: 'zLWtTv64KMOiopRJevijEjuLH5HgdhH1-RVBuvLn8Qor4zfGL7U7KL6ks3hhYJYME5vcuMuDcm5I7SER2HhYLNNIQw4N31Rs2z-KLD_sG11AxJ3c_h8vk9iS1QqyScIeY95Ur0-2qS9tX1AZLYK1Cm6C4x6g6mdYo2PyQ26RPBfjNC8Z_bIdf4I4Iz7l8lX_sH5uBxP9_7WC9D0RwKCByZTPQ68GBXEoxB64YtlbR8VMhxrQBDWzcQCYhMaThAMbQKMC6XEyVCVBfHevfmpJizSgdKM7NdynawGgMhyHzNFzmo_gA6lAF6IkPdCkDT-bfZxgWMrsFx6ldIVGVURJlw',
  oth: null,
};

// This will throw
await importJWK(jwk, 'RS256');
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Leaving null on such a JWK object would just make the import fail further on down the stack in node:crypto or WebCryptoAPI.

**Comment by panva** [comment]
In Browsers/Deno/Bun/Workerd/Edge Runtime

A JWK object with null as a value for `oth` is not valid as per its WebIDL definition.

Therefore, leaving such in and continuing on will fail with either one
- explicit oth being unsupported check
- failing the WebIDL serialization from `null` to [`sequence<RsaOtherPrimesInfo> oth`](https://w3c.github.io/webcrypto/#JsonWebKey-dictionary)

In `node:crypto#createPublicKey/createPrivateKey` this would not fail but in order to unify the behaviour across runtimes this check will remain as-is.
