### ISSUE TITLE
CryptoKey is not extractable

### ISSUE THREAD

**Issue by dreemhai** [panva/jose#595]
### What happened?

Hi,

I'm trying to export a private key that has been generated by generateKeyPair function.
```
  const { publicKey, privateKey } = await jose.generateKeyPair('ES256')
  const spPrivateKey = await jose.exportPKCS8(privateKey)
```

But it generates the following error:
```
Uncaught (in promise) TypeError: CryptoKey is not extractable
    at E (background.js:1:4247)
    at A (background.js:1:4737)
    at Object.P (background.js:1:5567)
    at background.js:1:332
```

### Version

v4.15.4

### Runtime

Node.js

### Runtime Details

node v19.7.0

### Code to reproduce

```js
import * as jose from 'jose'
const { publicKey, privateKey } = await jose.generateKeyPair('ES256')
const spPrivateKey = await jose.exportPKCS8(privateKey)
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
There's an option to have the key extractable in WebCryptoAPI runtimes.
