### ISSUE TITLE
JWKS Timeout : request timed out

### ISSUE THREAD

**Issue by ra-kesh** [panva/jose#596]
### What happened?

Getting the below `request timeout error` while trying to verify using a public JSON Web Key Set with next js 13 app router middlware and hanko . It was working perfectly fine 2 days ago but suddenly it's giving timeout most of the time now 

```
 [JWKSTimeout: request timed out] {
  code: 'ERR_JWKS_TIMEOUT',
  name: 'JWKSTimeout',
  message: 'request timed out'
}
```

### Version

4.15.3

### Runtime

Browser

### Runtime Details

Next 13.5.6 

### Code to reproduce

```js
import { NextResponse, NextRequest } from "next/server";

import { jwtVerify, createRemoteJWKSet } from "jose";

const hankoApiUrl = process.env.NEXT_PUBLIC_HANKO_API_URL;

export async function middleware(req: NextRequest) {
  const hanko = req.cookies.get("hanko")?.value;

  const JWKS = createRemoteJWKSet(
    new URL(`${hankoApiUrl}/.well-known/jwks.json`)
  );

  try {
    const verifiedJWT = await jwtVerify(hanko ?? "", JWKS);
    
  } catch (error) {
    console.error(error)
    return NextResponse.redirect(new URL("/login", req.url));
  }
}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
> It was working perfectly fine 2 days ago but suddenly it's giving timeout most of the time now

That's something to take up with your Network, its settings, and/or the operator of the JSON Web Key Set service.
