### ISSUE TITLE
question:  Creating unsigned tokens (alg: none)

### ISSUE THREAD

**Issue by marcuspoehls** [panva/jose#60]
Hi Filip,

is it possible to create an unsigned JWT using `alg: 'none'`?

I’m the maintainer of [futurestudio/hapi-jwt](https://github.com/futurestudio/hapi-jwt). The upcoming hapi version requires Node.js v12. While updating `hapi-jwt`, I want to switch to this `jose` package.

If possible, I would like to keep the option to create unsigned tokens in `hapi-jwt` :)

Thank you!

**Comment by panva** [comment]
It starts with creating them, then someone comes and asks for accepting them. 

I won’t be adding alg: none, i think it’s a mistake to mix secure and insecure algorithms in the same API.

I don’t see why you’d need the option for your module too, given what it’s for... many jose consumers aren’t aware of the unsigned JWS option and implementing it is a disservice to them. 

If you absolutely need it tho, base64url module and JSON.stringify plus string concatenation is all it takes, everything else this module takes care of.

**Comment by marcuspoehls** [comment]
OK, thank you for sharing your thoughts 👍
