### ISSUE TITLE
Cannot read properties of undefined (reading 'base64url')

### ISSUE THREAD

**Issue by alan19031216** [panva/jose#603]
### What happened?

Below is my code

```
        const secret = jose.base64url.decode(user.salt)
        const userJWT = await new jose.EncryptJWT({ id: user.id, email: user.email })
            .setExpirationTime('2h')
            .encrypt(secret)
```

This is my error msg

`TypeError: Cannot read properties of undefined (reading 'base64url')`

### Version

5.0.1

### Runtime

Node.js

### Runtime Details

node version 16.20.1

### Code to reproduce

```js
const secret = jose.base64url.decode(user.salt)
        const userJWT = await new jose.EncryptJWT({ id: user.id, email: user.email })
            .setExpirationTime('2h')
            .encrypt(secret)
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Can you post a full reproduction script?

**Comment by panva** [comment]
Please see the [README](https://github.com/panva/jose?tab=readme-ov-file#documentation) on how to import the module.

In ESM you're supposed to 

```
import * as jose from 'jose'
```

**Comment by panva** [comment]
Also, node version 16.20.1 is no longer supported on v5.x of jose, see [CHANGELOG.md](https://github.com/panva/jose/blob/main/CHANGELOG.md)

**Comment by alan19031216** [comment]
alright. thank you

**Comment by alan19031216** [comment]
> import * as jose from 'jose



> Also, node version 16.20.1 is no longer supported on v5.x of jose, see [CHANGELOG.md](https://github.com/panva/jose/blob/main/CHANGELOG.md)

I just tried in Node V16.20.1. So far looks good. I still need upgrade my node version?

**Comment by panva** [comment]
Yeah, Node.js v16.x is End-Of-Life since September 11th 2023.
