### ISSUE TITLE
suggestion: replace asn1.js with any updated fork

### ISSUE THREAD

**Issue by tabarra** [panva/jose#61]
**Describe the bug**
Using `jose` will sometimes throw `DeprecationWarning` due to the fact that the dependency `asn1.js` is outdated and seems abandoned (the fix PR is open since march/2018).

**Message**
```
(node:29508) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Environment:**
 - `jose` version: 1.18.1
 - node version: v12.13.0  

**Some reading material**
https://github.com/indutny/asn1.js/pull/116  
https://github.com/indutny/asn1.js/pull/103

**Comment by panva** [comment]
I don't trust forked releases but I'll see what I can do, but i don't believe asn1.js is abandoned or outdated, it's still "just" a deprecation warning. Let's give [at]indutny a [nudge](https://twitter.com/_panva/status/1214092441114042368) over a channel he follows first.

**Comment by panva** [comment]
All it takes is a [nudge](https://twitter.com/_panva/status/1214092441114042368).

**Comment by tabarra** [comment]
Hey @panva, a bit unrelated, but do you mind trying to nudge him again?  
Still getting `new Buffer()` deprecation warnings due to an outdated subdependnecy (bn.js).  
Issue: https://github.com/indutny/asn1.js/issues/120  
PR: https://github.com/indutny/asn1.js/pull/118

**Comment by panva** [comment]
I replied to the tweet thread again, but at this point it’s out of my hands.

**Comment by panva** [comment]
@tabarra so i went ahead, forked asn1.js and removed all its dependencies, including `bn.js` in favour of `BigInt`

The `1.23.0` release from yesterday already uses it - see https://bundlephobia.com/result?p=jose@1.23.0

**Comment by tabarra** [comment]
Very good job Panva!  
Thank you very much.
