### ISSUE TITLE
Bun: Export named 'diffieHellman' not found in module 'crypto'.

### ISSUE THREAD

**Issue by leifu1128** [panva/jose#615]
### What happened?

Export named 'diffieHellman' not found in module 'crypto'.

### Version

5.1.3

### Runtime

Other (I will specify below)

### Runtime Details

Bun, Svelte, Vite latest

### Code to reproduce

```js
// 1. create svelte project: https://bun.sh/guides/ecosystem/sveltekit

// 2. add to src/routes/+page.svelte
<script lang="ts">
	import * as jose from 'jose';
</script>

// 3. bun --bun run dev
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
https://github.com/panva/jose/issues/471#issue-1437490008
