### ISSUE TITLE
importPKCS8 working in Node, but throws error in Cloudflare workers

### ISSUE THREAD

**Issue by step135** [panva/jose#629]
### What happened?

**Error: Uncaught DOMException(DataError): Input was not an EC key.**

### Version

latest

### Runtime

Cloudflare Workers

### Runtime Details

latest everything

### Code to reproduce

```js
import * as jose from 'jose'

async function fce() {
	const private_key = ...
	const algorithm = 'ES256'
	const ecPrivateKey = await jose.importPKCS8(private_key, algorithm)
}
await fce()
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hi @step135 

> Error: Uncaught DOMException(DataError): Input was not an EC key.

Then the input is not an EC key to be imported with an ECDSA-based algorithm.

**Comment by step135** [comment]
I tried all of them and nothing worked. It is a secret key for firebase, so probably HS256 should be the right? But when I use HS256 it throws error **JOSENotSupported: Invalid or unsupported "alg" (Algorithm) value**.
