### ISSUE TITLE
HS256 not supported on Cloudflare Workers

### ISSUE THREAD

**Issue by step135** [panva/jose#630]
### What happened?

JOSENotSupported: Invalid or unsupported "alg" (Algorithm) value

### Version

5.2.0

### Runtime

Cloudflare Workers

### Runtime Details

npx wrangler dev (run locally)

### Code to reproduce

```js
import * as jose from 'jose'

async function fce() {
	const private_key = "-----BEGIN PRIVATE KEY-----..."
	const algorithm = 'HS256'
	const ecPrivateKey = await jose.importPKCS8(private_key, algorithm)
}
await fce()
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please open a Q&A Discussion thread instead. These issues are not bug reports.
