### ISSUE TITLE
question: Support for HSMs and/or non-extractable private keys?

### ISSUE THREAD

**Issue by christianlundkvist** [panva/jose#66]
First off, thank you so much for building/maintaining this great library! 😃👍

Question: In the signing functions for JWS exposed in this library it is required to pass in the private key into the function in order to sign a specific JWT. Are there any plans to also support signing with private keys that cannot be extracted, such as those created on HSMs or secure enclaves? Or is that deliberately out of scope for this library?

**Comment by panva** [comment]
It is out of scope, at least until node supports engines natively.

**Comment by christianlundkvist** [comment]
Thanks for the answer @panva, that makes sense!
