### ISSUE TITLE
[Usage with Vitest/JSDOM] payload must be an instance of Uint8Array

### ISSUE THREAD

**Issue by raulfdm** [panva/jose#671]
### What happened?

Hey folks 👋 

I'm opening this issue just for cross-reference because I couldn't find anything in the repo.

I was writing a tiny function that generates a signed JWT from a payload and when I tried to write a unit test, it started failing:

```text
TypeError: payload must be an instance of Uint8Array
 ❯ new FlattenedSign node_modules/jose/dist/node/esm/jws/flattened/sign.js:14:19
 ❯ new CompactSign node_modules/jose/dist/node/esm/jws/compact/sign.js:5:27
 ❯ SignJWT.sign node_modules/jose/dist/node/esm/jwt/sign.js:12:21
 ❯ Module.generateJWT src/generate-jwt.js:20:6
     18|     .setProtectedHeader({ alg: "RS256" })
     19|     .setExpirationTime("5m") // 5 minutes from now
     20|     .sign(privateKey);
       |      ^
     21|
     22|   return jwt;
 ❯ src/generate-jwt.test.js:13:17
```

After some investigation, I realize that this happened because I had `JSDOM` as test environment. The `Uint8Array` class used to encode the payload isn't the same when the Sign class use to check if it's instance of `Uint8Array`

<details>
<summary>If you're curious, watch this video</summary>

https://github.com/panva/jose/assets/12464600/23a724b2-b9fd-46d2-b8b9-016e2d47ecef

</details>

I don't think there's nothing to you to do here though. Just opened this to have some cross reference because I couldn't find this problem reported anywhere.

### Links

- https://github.com/raulfdm/jsdom-jose-crypto-bug
- https://github.com/jsdom/jsdom/issues/3711

### Version

5.2.4

### Runtime

Node.js

### Runtime Details

node 20.10.0

### Code to reproduce

```js
- https://github.com/raulfdm/jsdom-jose-crypto-bug
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
jest is also notorious for this nonsense with jsdom #441

As you said, there's nothing I can do here but ask myself why do test tools insist on messing with globally exposed classes and why is this acceptable for its users.

**Comment by raulfdm** [comment]
@panva Found the guilty: https://github.com/vitest-dev/vitest/issues/5685

I don't have any context about why vitest needs to do such global class manipulation, but it's their fault.
