### ISSUE TITLE
Reference error: Key is not defined

### ISSUE THREAD

**Issue by karannakraTR** [panva/jose#676]
### What happened?

I am trying to verify my JWT token using the method `jose.jwtVerify` which expects `token` as first argument and  `key` as a second argument. But this function throws the error `Reference error: key is not defined`.

Possible reason of the bug:

SCREEN SHOTS FROM V5.3.0

![image](https://github.com/panva/jose/assets/109527945/2c75759c-c2c3-4395-862c-9d8ffed88517)

When jose is compiled, The function falttenVerify changes the argument name of `key` to `z` but on line no.84 code is still trying to find the variable named key which is now changed to `z` Due to which it throws the error `key ` is not found.

![image](https://github.com/panva/jose/assets/109527945/8730512b-078c-48de-96bf-439f3f452ad6)

![image](https://github.com/panva/jose/assets/109527945/43f010ea-3ba9-42eb-83df-7762b8222133)

I don't see the re-assignment of variable `z` to `key` anywhere before it's usage.

But when I downgrade the version from 5.3.0 to 5.2.4. It works just fine and the argument is now not changed to z and when requested in the code expression below it is able to find that variable.

![image](https://github.com/panva/jose/assets/109527945/40868b9b-5a17-44b2-b94c-ac37b2cedbaf)

### Version

v5.3.0

### Runtime

Node.js

### Runtime Details

Node: V18.20.2, NPM: V10.5.0, PNPM: V9.1.0, MacOS: 13.6.7 (22G720)

### Code to reproduce

```js
const JWKS = jose.createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'))

const { payload, protectedHeader } = await jose.jwtVerify(jwt, JWKS, {
  issuer: 'urn:example:issuer',
  audience: 'urn:example:audience',
})
console.log(protectedHeader);
console.log(payload);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hello @karannakraTR 

please provide a reproduction sample project repo where this can be reproduced with steps on how to build your minified bundle etc.
