### ISSUE TITLE
5.6.0 normalizePrivateKey

### ISSUE THREAD

**Issue by dezerb** [panva/jose#690]
### What happened?

During import of auth.js there is exception while loading jose (version 5.5.0 is not affected by this)

```
│ ../../node_modules/jose/dist/node/esm/lib/encrypt_key_management.js
│ Attempted import error: 'normalizePublicKey' is not exported from '../runtime/normalize_key.js' (imported as 'normalize').
│ 
│ Import trace for requested module:
│ ../../node_modules/jose/dist/node/esm/lib/encrypt_key_management.js
│ ../../node_modules/jose/dist/node/esm/jwe/general/encrypt.js
│ ../../node_modules/jose/dist/node/esm/index.js
│ ../../node_modules/@auth/core/jwt.js
│ ../../node_modules/@auth/core/lib/init.js
│ ../../node_modules/@auth/core/lib/index.js
│ ../../node_modules/@auth/core/index.js
│ ../../node_modules/next-auth/index.js
```

### Version

5.6.0

### Runtime

Browser

### Runtime Details

macos, node 20, next14 

### Code to reproduce

```js
import { auth } from '@/auth';
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
sigh. Optimized too soon. Will fix shortly.

**Comment by panva** [comment]
Please provide a cloneable project and steps to reproduce the issue.

**Comment by panva** [comment]
https://github.com/panva/jose/releases/tag/v5.6.1

**Comment by dezerb** [comment]
@panva thanks for fast fix, tested now it works like a charm 🎉
