### ISSUE TITLE
createRemoteJWKSet throws error on Bun

### ISSUE THREAD

**Issue by ThatOneCalculator** [panva/jose#702]
### What happened?

From the documentation: https://github.com/panva/jose/blob/HEAD/docs/functions/jwks_remote.createRemoteJWKSet.md#returns-1

This throws an error with Bun

### Version

5.6.3

### Runtime

Other (I will specify below)

### Runtime Details

Bun 1.1.21, Linux x86_64

### Code to reproduce

```js
import { URL } from "node:url";
jose.createRemoteJWKSet(new URL("https://www.googleapis.com/oauth2/v3/certs"));
```

Throws

(specifically hovering over `new URL("https://www.googleapis.com/oauth2/v3/certs")`)

```
Argument of type 'import("url").URL' is not assignable to parameter of type 'URL'.
  Type 'URL' is missing the following properties from type 'URL': createObjectURL, revokeObjectURL, canParse
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Use the runtime's native global URL implementation.

**Comment by ThatOneCalculator** [comment]
But I am! Bun uses `node:` namespace imports for compatibility reasons, but that uses Bun's impl.

**Comment by panva** [comment]
Please open an issue in Bun. I see now you're not getting a runtime error but a type error, either way - nothing I can help with here.

**Comment by wparad** [comment]
@ThatOneCalculator https://github.com/oven-sh/bun/issues/9634
