### ISSUE TITLE
bug: invalid token 

### ISSUE THREAD

**Issue by sandeepkj90** [panva/jose#71]
You updated 'jose' package yesterday in github but still changes not received on npm install of 'JOSE' package. So in key_object.js file showing error as unexpected token for 0n.

**Comment by panva** [comment]
Sorry, but there's no issue, no bug. `0n` is a valid BigInt syntax.


```
❯ node -v                                
v10.13.0

❯ node -e 'console.log(0n === BigInt(0))'
true
```

You should reconsider transpiling your project's node_module dependencies or take it up with whatever you're using to do so.

**Comment by sandeepkj90** [comment]
Thanks. Sorry I was using node 8 version.

**Comment by panva** [comment]
Node v10.13.0 is the minimal [declared](https://github.com/panva/jose/blob/v1.23.0/package.json#L91-L93) and [documented](https://github.com/panva/jose/tree/v1.23.0#usage) Node.js runtime version.
