### ISSUE TITLE
Inconsistent Error Messages 

### ISSUE THREAD

**Issue by quesurifn** [panva/jose#712]
### What happened?

When using JWE with a JWT via `compactEncrypt` and `compactDecrypt` error messages for an expired token is `ERR_JWT_EXPIRED` if we just use regular JWS, we get a long form error message such as `"\"exp\" claim timestamp check failed". 

Short form error messages are generally a good idea in this context, because filters and middleware can key off of them. If however, they are inconsistent across APIs, then they have no use for developers. 

### Version

4.13.1

### Runtime

Node.js

### Runtime Details

v20.8.0

### Code to reproduce

```js
Coming soon.
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by quesurifn** [comment]
Bare with me. I'll add more details before EOD.

**Comment by panva** [comment]
compactDecrypt is unaware of what the resulting plaintext is. jwtDecrypt validates the plaintext as a JWT claims set.

**Comment by quesurifn** [comment]
But compactDecrypt is aware of the claims because it validates them. That's where the issue lies. We get ERR_JWT_EXPIRED using JWE, but `exp claim failed timestamp check` using jwtValidate.

**Comment by panva** [comment]
compactDecrypt does not validate a JWT claims set because it is not a JWT method

**Comment by quesurifn** [comment]
Apologies. You're right. We were using `jose.jwtDecrypt` and now we're using `jose.jwtVerify`. Those are the two methods with discrepancies with the error messaging.

**Comment by panva** [comment]
When it comes to JWT Claims Set validation they are identical.

**Comment by quesurifn** [comment]
That's not our experience at all. If they were identical our refresh token pipeline wouldn't have broken due to the different error messages and I wouldn't have had two different error messages to show you. I'll dive into the code when I have time and submit a fix but that could be weeks.

**Comment by panva** [comment]
Better start with a reproduction

**Comment by panva** [comment]
```js
import * as jose from "jose";

const kp = await jose.generateKeyPair("ES256");
const sk = await jose.generateSecret("A128CBC-HS256");

const jwe = await new jose.EncryptJWT()
  .setProtectedHeader({ alg: "dir", enc: "A128CBC-HS256" })
  .setExpirationTime("10 minutes ago")
  .encrypt(sk);

const jws = await new jose.SignJWT()
  .setProtectedHeader({ alg: "ES256" })
  .setExpirationTime("10 minutes ago")
  .sign(kp.privateKey);

console.log({ jwe, jws });

try {
  await jose.jwtDecrypt(jwe, sk);
} catch (e) {
  console.log("jwe error");
  console.log(e);
}

try {
  await jose.jwtVerify(jws, kp.publicKey);
} catch (e) {
  console.log("jws error");
  console.log(e);
}
```

output

```
{
  jwe: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..EQp17aFbd7GddRpnYGlhBA.X0Eu_Sj9xP4dHh46SPzZgTiaKsbKFHGaSHobpKaKmM4.8PyGZhq0XTwsPCL_a4D7ZA',
  jws: 'eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3MjUwNTAyMTN9.H3hTyCh8PoMYknj6AYLUaZXK1CV9FF8OwghAth-Ic74RhqjFOEsGlP5Ue_Q991CuuRiBECQuYLjs9aN5EeGUxQ'
}
jwe error
JWTExpired: "exp" claim timestamp check failed
    at default (file:///Users/panva/repo/provider/node_modules/jose/dist/node/esm/lib/jwt_claims_set.js:89:19)
    at Module.jwtDecrypt (file:///Users/panva/repo/provider/node_modules/jose/dist/node/esm/jwt/decrypt.js:6:21)
    at async file:///Users/panva/repo/provider/some.mjs:19:3 {
  code: 'ERR_JWT_EXPIRED',
  claim: 'exp',
  reason: 'check_failed',
  payload: { exp: 1725050213 }
}
jws error
JWTExpired: "exp" claim timestamp check failed
    at default (file:///Users/panva/repo/provider/node_modules/jose/dist/node/esm/lib/jwt_claims_set.js:89:19)
    at Module.jwtVerify (file:///Users/panva/repo/provider/node_modules/jose/dist/node/esm/jwt/verify.js:9:21)
    at async file:///Users/panva/repo/provider/some.mjs:26:3 {
  code: 'ERR_JWT_EXPIRED',
  claim: 'exp',
  reason: 'check_failed',
  payload: { exp: 1725050213 }
}
```

There is no reason for the error codes names or messages to be different between the two methods since they use the exact same claim set validation routine. Feel free to come back with a reproduction if you find an issue.
