### ISSUE TITLE
AWS Lambda Error: ERR_OSSL_ASN1_HEADER_TOO_LONG with Key Encoding (Node.js 20.x, ARM64)

### ISSUE THREAD

**Issue by 2820402** [panva/jose#714]
### What happened?

I’m encountering an issue when deploying my Node.js 20.x application to AWS Lambda with ARM64 architecture. The code works perfectly in my local environment but throws the following error in production:

```bash
Error: error:0680007B:asn1 encoding routines::header too long
    at createPublicKey (node:internal/crypto/keys:619:12)
    at fromSPKI (/var/task/node_modules/jose/dist/node/cjs/runtime/asn1.js:43:61)
    at importSPKI (/var/task/node_modules/jose/dist/node/cjs/key/import.js:13:35)
    at validateJwt (/var/task/src/handlers.js:148:55)
    at handleConnect (/var/task/src/handlers.js:189:34)
    at Runtime.handler (/var/task/src/handlers.js:49:30)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29) {
  opensslErrorStack: [
    'error:0688010A:asn1 encoding routines::nested asn1 error',
    'error:06800066:asn1 encoding routines::bad object header'
  ],
  library: 'asn1 encoding routines',
  reason: 'header too long',
  code: 'ERR_OSSL_ASN1_HEADER_TOO_LONG'
}
```

# Things I’ve Checked:
+ Verified the key format and ensured it's in PEM format. No issues with the key format locally.
+ Ensured the key file is included in the Lambda deployment package and is in the correct path.
+ Verified that the jose library version is the same in Lambda and locally.
+ Checked that any environment variables related to the key are correctly set up in Lambda.

# Here is the code:

```tsx
const validateJwt = async (jwt: string): Promise<boolean | ExtendedPayload> => {
    try {
        console.log(jwt, process.env.PUBLIC_KEY) // I confirm both are printed in logs
        const publicKey = await importSPKI(
            process.env.PUBLIC_KEY as string,
            'ES512'
        );
        const { payload } = await jwtVerify(jwt, publicKey, {
            issuer: '...',
        });
        return payload as ExtendedPayload;
    } catch (e) {
        console.log(e);
        return false;
    }
};
```

### Version

v5.8.0

### Runtime

Node.js

### Runtime Details

Node.js 20.x, ARM64

### Code to reproduce

```js
const validateJwt = async (jwt: string): Promise<boolean | ExtendedPayload> => {
    try {
        console.log(jwt, process.env.PUBLIC_KEY) // I confirm both are printed in logs
        const publicKey = await importSPKI(
            process.env.PUBLIC_KEY as string,
            'ES512'
        );
        const { payload } = await jwtVerify(jwt, publicKey, {
            issuer: '...',
        });
        return payload as ExtendedPayload;
    } catch (e) {
        console.log(e);
        return false;
    }
};
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hi @2820402 

You'll have to check with AWS. But, as a workaround you may want to use a different key format such as JWK with the importJWK function to obtain a KeyObject instead.

**Comment by wparad** [comment]
Is there a reason that `importSPKI` wouldn't be supported by this library for some arbitrary installation? I'm concerned about people upgrading to Node20 from an earlier version and then breaking. Is the node version not relevant here? E.g. is importSPKI not supported on any lambda runtime or any runtime using arm?

At the very least could we expect that the error message to better represent the problem "e.g. this function is not supported on this operating system"? So that on upgrade/runtime changes, it is clear that the problem is the runtime and not the publickey/configuration?

**Comment by panva** [comment]
FWIW, can you provide the public key in question?

**Comment by panva** [comment]
FWIW, can you (@2820402) provide the public key in question?

@wparad You can see clearly the stack trace ends with `crypto.createPublicKey` and the error comes from OpenSSL.

What I suspect is that AWS in their Lambda Node.js build links against an OpenSSL configured with different configuration than Node.js ships with by default. That's not something that neither Node.js nor this module can account for, should document, or should in any way explicitly call out.

**Comment by wparad** [comment]
I'm concerned about a "pit of failure" here, where everything works on a previous version, and then on upgrade it breaks. It's also possible this isn't a problem with node:crypto at all nor OpenSSL, but the public key. For instance, I wonder if this works on non-arm or non-node20. @2820402 does your public key work on node18.x, node16.x, or on node20.x for the x86 architecture?

**Comment by panva** [comment]
I'm also not able to reproduce on Lambda 20.x ARM64 with neither supported key type nor excessive (10240bit) RSA key sizes.
