### ISSUE TITLE
Error: Parsing file C:\Users\User\node_modules\jose\dist\browser\index.js: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by chanming9** [panva/jose#726]
### What happened?

i tried to imported the jose library to a typescript, follwing the import method below,  

```
import * as Jose from 'jose';

```
while the visual studio code doesnt show any issues, the game engine that i'm using (cocos creator 2.4.6 ), had the issue below:
![image](https://github.com/user-attachments/assets/84c5f53e-bd39-4fdf-962f-da1fe8b88d03)
i had reinstalled few times, but it keeps popping up this same issue over and over again

### Version

v5.9.4

### Runtime

Other (I will specify below)

### Runtime Details

Node.js v21.4.0, cocos creator v2.4.6, using typescript

### Code to reproduce

```js
import * as Jose from 'jose';
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Feels like something to take up with the engine rather than the library.
