### ISSUE TITLE
Error importing a PEM public key that is correctly imported by crypto.createPublicKey

### ISSUE THREAD

**Issue by ecamellini** [panva/jose#730]
### What happened?

I am trying to import a PEM-formatted public key encoded in base64. 
I do the following:
1. decode the base64 getting a PEM string
2. import this PEM string 

However, `importSPKI` fails with a `TypeError: "spki" must be SPKI formatted string`. 
Importing the same key with `crypto.createPublicKey` succeeds.

**I could reproduce it only with these specific public key and steps**: 
- if I take another PEM, encode it in base64, and run the same code, it works
- if I decode it e.g., in the cli, copy-paste the PEM into a string, and import it, it works

### Version

5.9.4

### Runtime

Node.js

### Runtime Details

20.17.0

### Code to reproduce

```js
import * as crypto from "crypto";
import * as jose from "jose";

const algorithm = "RS256";
    const encodedPEM = "LS1rZXlQYXRoIC9Vc2Vycy9nYWxhbGVzL2Rldi9taXNjL2NsaWVudEFzc2VydGlvbi9rZXkvY2xpZW50LWFzc2VydGlvbi5yc2EucHJpdgotLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLQpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZxSUwwTXdKaU5JNnZTbFltNy91CkVQd1drTDBzNzlSNUJ4bmkzRXVPay93RXkyOFBCMk5ReHppVDNqRFpkTHFqTFJ0OHNYWXAwUzBMWTVlUk5xRDkKV3lQU2JCSCtRMGg2cU1QUFRoVWcrSXA1Ly9vMWF5QkhPSE14eWJyR3RGYXNSa2NYakEyVitZbWRXanBlWHBuVwpQeEo3ZTRJYUljanh4QmdFUG5zcTBhN1Z5OUdTWElsZk9zaEZ0Q2tkc1o3V25hbmVXRzNnK2ZVSUttSTlHcGVSCk42b0dSVDE3ckY4d3R1L2JxQVV0L0taUm9CeGVpMERWQkhnaytsdEpzVmx0MTRQcXRCbnpTdmluMXRvVEhpM2wKbnhyNUJBZnVZc25YRHZaTmVNeXU4U3pTQy9kKzNBQUFtY3JWSmNXTTlHZVU4OXpVeHlUUWlKbmx5SDJQZjFicQpaUUlEQVFBQgotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=";

const PEM = Buffer.from(encodedPEM, "base64").toString("utf8");

crypto.createPublicKey(PEM) // This works and creates a crypto.KeyObject
await jose.importSPKI(PEM, "RS256") // TypeError: "spki" must be SPKI formatted string
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
It's not expected that all createPublicKey inputs work in importSPKI. For importSPKI and importPKCS8 you want the private key in a full PEM format with the closing and ending envelope as shown in the [example](https://github.com/panva/jose/blob/v5.9.6/docs/key/import/functions/importSPKI.md#example).
