### ISSUE TITLE
Node crypto blocks the event loop

### ISSUE THREAD

**Issue by ChadKillingsworth** [panva/jose#77]
**Is your feature proposal related to a problem? Please describe.**
Unfortunately node crypto operations block the event loop. We use signed JWTs for internal service authentication and end up signing thousands of JWTs. For performance, we've had to fork and write our own JWT library simply to offload the crypto operations to separate threads in Node JS using https://github.com/ronomon/crypto-async.

To assist this work I contributed back the RSA sign and verify functions to the crypto-async library: https://github.com/ronomon/crypto-async/pull/7

**Describe the solution you'd like**
A library such as crypto-async is definitely not something ready for every use case. However, I'd like the option to utilize it with this library. Specifically, I'm simply looking for extension points so that I can use a custom crypto library.

**Describe alternatives you've considered**
Because the node native crypto operations are blocking, there are very few options. I'd rather contribute to a standards based open source library that supports this than maintain my own.

**Additional context**
While guidance would be needed on the correct approach, I'd be willing to do the work to add this feature.

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Using or supporting anything but native crypto is out of scope for this library.

@ChadKillingsworth You can certainly push your sign/verify jose code that uses regular node `crypto` to a [worker thread](https://nodejs.org/api/worker_threads.html). Have one per process that you push your blocking code to.

**Comment by ChadKillingsworth** [comment]
We benchmarked worker threads and they didn't perform near as well as native threads.
