### ISSUE TITLE
Type checking error for generate function

### ISSUE THREAD

**Issue by WangHansen** [panva/jose#80]
**Describe the bug**

TypeScript error: Argument of type '"string"' is not assignable to parameter of type '"oct"'

**To Reproduce**

Steps to reproduce the behaviour:

1.  create a keystore with `new jose.JWT.KeyStore()`
2.  create a type alias `type Algorithm = "RSA" | "EC" | "OKP" | "oct";`
3.  create a function `generateKey`: 
```javascript
function generateKey(alg: Algorithm) {
  return keystore.generateSync(alg, "P-256");
}
```
Reproduction link: https://codesandbox.io/s/laughing-shockley-hlpr1?file=/src/index.ts

**Expected behaviour**
Expect no error with type checking

**Environment:**
 - `jose` version: v1.26.0
 - node version: v12.13.1

**Additional context**

 - [x] the bug is happening on latest `jose` too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
@WangHansen please see the [`fix-80`](https://github.com/panva/jose/tree/fix-80) branch and let me know if it resolves the issue.

**Comment by WangHansen** [comment]
@panva Sorry for the late reply, it works now, thank you for the fast fix. It apparently has something to do with TypeScript itself as well, see [this](https://github.com/microsoft/TypeScript/issues/38201). But with your fix, it should work now, thanks again!
