### ISSUE TITLE
JWEDecryptionFailed: decryption operation failed

### ISSUE THREAD

**Issue by therealsqvad** [panva/jose#82]
Hello everyone.
You need to decrypt the JWE and get the data.
Checked through JAVA - using the existing key it is possible to decrypt the message, but in nodejs it does not work
The library gives an error
_JWEDecryptionFailed: decryption operation failed_
the key is parsed, the message is validated by JWE, it already crashes during decryption

An error does not occur in the function at the time of return
aes_gcm.js
```
const decrypt = (size, {[KEYOBJECT]: keyObject}, ciphertext, {iv, tag = Buffer.alloc (0), aad = Buffer.alloc (0)}) => {
  const key = keyObject.asInput? keyObject.asInput (): keyObject
  checkInput (size, iv, tag)

  try {
    const cipher = createDecipheriv (`aes - $ {size} -gcm`, key, iv)
    cipher.setAuthTag (tag)
    cipher.setAAD (aad)

    **return Buffer.concat ([cipher.update (ciphertext), cipher.final ()])**
  } catch (err) {
    throw new JWEDecryptionFailed ()
  }
}
```

My code
```
const key = fs.readFileSync(keyFile);
const enc = encryptedData
try {
  const key = jose.JWK.asKey(keyData);
  jose.JWE.decrypt(
    enc,
    key,
  );
} catch (error) {
  console.log('error: ', error);```

**Comment by panva** [comment]
Please provide something tangible - an actual JWE token, the secret key, the java code that produced it, etc

**Comment by therealsqvad** [comment]
Unfortunately, JAVA code that can decrypt under NDA
And the existing JWE contains sensitive data

**Comment by panva** [comment]
In such case I cannot help you. All I can say that this implementation is checked against the [IETF RFC7520](https://tools.ietf.org/html/rfc7520) so it is likely issue exists in your java code.

**Comment by therealsqvad** [comment]
[Here is the decryption function in JAVA](https://github.com/PaylinePaymentMethod/payment-method-samsung-pay/blob/79802feb728241912a4a4747221bae87ac118973/src/main/java/com/payline/payment/samsung/pay/utils/JweDecrypt.java), which can be decrypted using the key. The encryption function is not available to me

**Comment by panva** [comment]
That's of no use to me. I just checked [Nimbus](https://connect2id.com/products/nimbus-jose-jwt) produced JWEs and AES GCM works with no issues, ergo - this library is interoperable with other JWE conform libraries. Your JWE producer is likely implementing JWE wrong.

**Comment by panva** [comment]
Actually, looking at the decrypt code - i see `RSA_ECB_PKCS_1_PADDING` is used, that doesn't match any JWE key management algorithm. Now if the producer uses that and says it's e.g. RSA-OAEP then the key management decrypt function will fail, a random CEK will be generated ([here, as it should](https://github.com/panva/jose/blob/v1.27.0/lib/jwe/decrypt.js#L137-L145) according to JWE) and pushed to the content decryption path. That means you will get a decrypt failure on the content part but your problem is actually key wrapping.
