### ISSUE TITLE
JWK generate does not recognize options object

### ISSUE THREAD

**Issue by qin-guan** [panva/jose#84]
**Describe the bug**

when running 

```JWK.generateSync("RSA", 2048, {use: 'enc'})```

it produces error 

```
TypeError: parameters argument must be a plain object when provided
    at asKey (/home/runner/JOSE/node_modules/jose/lib/jwk/import.js:39:11)
    at Object.generateSync (/home/runner/JOSE/node_modules/jose/lib/jwk/generate.js:40:14)
    at /home/runner/JOSE/index.js:11:5
    at Script.runInContext (vm.js:131:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
```

**To Reproduce**

Steps to reproduce the behaviour:

1. Use JWK.generate/generateSync with options 

**Expected behaviour**

should not produce error 

**Environment:**
 - `jose` version: [e.g. v1.0.0]

1.27.1

 - node version: [e.g. v12.0.0]

v12.16

**Additional context**

 - [x] the bug is happening on latest `jose` too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

i do not seem to be getting this issue on v12.18.0

the code which produced the error was run on repl.it

**Comment by panva** [comment]
I cannot reproduce your issue.

```
> JWK.generateSync("RSA", 2048, {use: 'enc'})
RSAKey {
  e: 'AQAB',
  kid: 'wF26_ap9LaT5mE7b5BYQpCoJGLrPQsNp73QISRWOzcs',
  kty: 'RSA',
  n: 'uYNvsVNOf8Ze5bIE5A_94XsY_FcodotxQ93gA0yA6iHwBhrDDjp2whqAOFNmxLPHBXq4wrxaMSstcip_hOJxgOhInZncGfbr6Zg0V7zk_NbwjeoXckzrUO9RBSIX-e-CBdg313Uc1gMBOiVN_RAWOC8toDMMbQBO01RSEplp2qKSGpIsRei4oyA0PQ68dNA9TkyDrBA0jrC7PW7XBup-W_4wnH0dWWmugmKgUcbODL8OxDB_-fKC28WH1SH4kF6Sm7Io5FR7uuLBTEyUhZtFs4pcG8Mye5-IL7rhuT7qxmNK_COs5T7eBrl71m5-EuIdgPmZBNpeFLhzBSBjM8UGmw',
  use: 'enc'
}


❯ node -v
v12.16.0
```

**Comment by panva** [comment]
I can reproduce this on `repl.it` but honestly, don't know what exact runtime they use given that in their repl `({}).constructor === Object` is false.

**Comment by qin-guan** [comment]
running `process.versions` shows that it’s running on node v12.16.3, is there a issue with this version?

**Comment by panva** [comment]
No, when i run in node repl its okay. Its just their weird runtime repl.

**Comment by qin-guan** [comment]
hmm okay, i will ask around and see if anyone at repl.it is able to resolve this

**Comment by masad-frost** [comment]
This was fixed a few weeks ago. Just thought I'd let you know
