### ISSUE TITLE
asn1.js not found on registry

### ISSUE THREAD

**Issue by thibault-lr** [panva/jose#90]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behaviour:

1.  yarn add jose

**Expected behaviour**
Package is installed

**Environment:**
 - `jose` version: [e.g. v1.24.1]
 - node version: [e.g. v12.16.1]

**Additional context**
error An unexpected error occurred: "https://registry.yarnpkg.com/@panva/asn1.js/-/asn1.js-1.0.0.tgz: Request failed \"404 Not Found\"".

**Comment by panva** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5
